flowchart LR

   DEM[("Elevation Model")] --> |Collection</br>Input| PSlope[[Slope]] --> |Nested<br/>Process<br/><br/><i>Collection</br>Output</i>| slope{slope}
   DEM[("Elevation Model")] --> |Collection</br>Input| PAspect[[Aspect]] --> |Nested<br/>Process<br/><br/><i>Collection</br>Output</i>| aspect{aspect}
   Permafrost[("Permafrost")] --> |Collection</br>Input| extent{extent}
   Permafrost[("Permafrost")] --> |Collection</br>Input| content{content}
   LandCover[("Land Cover")] --> |Collection</br>Input| lc{lc}
   Geology[("Surface Geology")] --> |Collection</br>Input| qcode{qcode}

   subgraph PassThrough
      subgraph DEM Slope
         slope --> |0..3.5| s1((1)) --> s
         slope --> |3.5..8.7| s3((3)) --> s
         slope --> |8.7..17.6| s5((5)) --> s
         slope --> |17.6..36.4| s7((7)) --> s
         slope --> |36.4..| s10((10)) --> s
      end

      subgraph DEM Aspect
         aspect --> |315..360, 0..45| a1((1)) --> a
         aspect --> |45..135, 225..315| a5((5)) --> a
         aspect --> |135..225| a10((10)) --> a
      end

      subgraph Surface Geology
         qcode --> |Ql| g0((0)) --> g
         qcode --> |Qra,Qi,Qrc,Qrd,Qre| g1((1)) --> g
         qcode --> |Qrb,Qaf,Qat,Qcb,Qfp,Qgmr| g3((3)) --> g
         qcode --> |Qcc,Qcd,Qel,Qm1,Qm2,Qm3,Qm4,Qw1,Qw2| g5((5)) --> g
         qcode --> |Qes,Qgm| g7((7)) --> g
         qcode --> |Qed,Qgl,Qu| g10((10)) --> g
      end

      subgraph Permafrost Content
         content --> |l| cl((1)) --> c
         content --> |m| cm((5)) --> c
         content --> |h| ch((10)) --> c
      end

      subgraph Permafrost Extent
         extent --> |c| ec((1)) --> e
         extent --> |d| ed((5)) --> e
         extent --> |s| es((7)) --> e
         extent --> |i| ei((10)) --> e
      end

      subgraph Land Cover
         lc --> |0,1,2,3,4,5,11,13,15| lc1((1)) --> l
         lc --> |6,7,8,9,10,12,14| lc5((5)) --> l
         lc --> |16| lc10((10)) --> l
      end

      s --> |"30%"| Sus
      a --> |" 5%"| Sus
      g --> |"30%"| Sus
      c --> |"20%"| Sus
      e --> |" 5%"| Sus
      l --> |"10%"| Sus
   end

   Sus("susceptibility") --> |Ad-hoc<br/>Workflow<br><br/>Collection<br/>Output| Client{{Client}}
