[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

=== Overview

Compliance testing for $standard_name$ and similar standards must answer three questions:

.  Are the capabilities advertised through the API Description compliant with the standard?

.  Does the API implement those capabilities as advertised?

.  Do the resources returned by the micro-services meet the structure and content requirements of the standard?

Further complicating the issue, an API may expose resources in addition to those defined by the standard.  A test engine must be able to traverse the API description document, identify test points, and ignore resource paths which are not to be tested.  The process for identifying test points is provided in Section A.4.3.

=== Conventions

The following conventions apply to this Abstract Test Suite:

==== Path Templates

Path templates are used throughout these test suites.  Path templating refers to the usage of curly braces “{}” to mark a section of a URL path that can be replaced using path parameters.  The terms used to describe portions of these templates are based on the URL syntax described in RFC 3986.

*  scheme: http | https

*  authority: DNS name of the server with optional port number

*  path: The slash delimited identifier for a resource on the server

*  query: query parameters following the "?" character

*  fragment: identifies an element within the resource. Preceded by the "#" character

==== API Description Document

The $standard_name$ standard does not mandate a standard format for the API Description Document.  However, some form of standard is needed if tests are to be accurately described and implemented.  Therefore, this Abstract Test Suite asserts that the API Description document is compliant with OpenAPI 3.0.  This Test Suite will be updated if and when an alternative is commonly adopted.

==== Resource Encodings

The $standard_name$ standard does not mandate a standard encoding for resources returned by the API. Yet a compliance test requires some minimal level of expected behavior. Therefore, this Abstract Test Suite asserts that the API returns resources encoded in HTML and GeoJSON. Since no compliance test suite exists for these encodings at this time, the resources shall be presented to the test operator for human inspection.  

==== Processing Security Objects

OpenAPI does not provide a standard way to associate a security requirement with a single server URI.  Therefore, $standard_name$ compliance tests will have to make that association through the runtime challenge-response transaction.  At this time the role of the Security Objects should be considered advisory.

Security Requirements can be defined at both the OpanAPI root level and at the Operation Object level. The following rules should be followed to understand the scope of a Security Requirement:

* The Security Requirements defined at the root level are the default requirements for all operations and servers.

* If Security Requirements are defined at the Operation level, then those Requirements, and not the ones defined at the OpenAPI level, shall be used with that operation.

* An empty set of Security Requirements at the Operation level indicates that there are no security requirements for that operation.

Note: this allows operations to opt-out of security requirements defined at the OpenAPI level.

==== Parameters

The following observations apply for $standard_name$ parameters:

. $standard_name$ does not use cookies.

. Query parameters follow common Web practice

. Header parameters are restricted to custom headers

. For path parameters, the name of the parameter must match the name of the variable in the path template in the path object

Parameters are defined at the Path Item and Operation level.  Parameters defined at the Path Item level must apply to all operations under that Path item. These parameters may be modified at the Operation level but they may not be removed.

==== Testable Paths

A testable path is a path which corresponds to one of the paths defined in the $standard_name$ specification. There are three alternatives for making this determination:

. The path URI matches – this is the simplest approach but may be subject to error

. Use mandatory tags in the tags field of the Operation Object

. Use standardized operation ids for the operationId field of the Operation Object

A testable path is validated against the rules for that path.  At a minimum that includes:

. Building a list of all parameters which are defined in the standard

. Validate that the mandatory parameters are present and required

. Validate type, format, etc. for each parameter in the list.

. Validate that there are no mandatory parameters which are not on the list.

=== Requirements Trace Matrix

[width="100%"]
|====================
| *Requirement 1:* API Landing Page Operation +
  The server SHALL support the HTTP GET operation at the path /. +
  Tests: A.4.2.1
| *Requirement 2:* API Landing Page Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema root.yaml and include at least links to the following resources: +
 - /api (relation type 'service') +
 - /conformance (relation type 'conformance') +
 - /collections (relation type 'data') +
Tests: A.4.2.2 +
| *Requirement 3:* API Definition Operation +
The server SHALL support the HTTP GET operation at the path /api. +
Tests: A.4.2.3 +
| *Requirement 4:* API Definition Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The server SHALL return an API definition document. +
Tests: A.4.2.3, A.4.2.4, A.4.4.1 +
| *Requirement 5:* Conformance Class Operation +
The server SHALL support the HTTP GET operation at the path /conformance. +
Tests: A.4.4.2 +
| *Requirement 6:* Conformance Class Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema req-classes.yaml and list all $standard_name$ requirements classes that the server conforms to. +
Tests: A.4.4.3 +
| *Requirement 7:* HTTP 1.1 +
The server SHALL conform to HTTP 1.1. +
If the server supports HTTPS, the server SHALL also conform to HTTP over TLS. +
Tests: A.4.1.1 +
|====================

=== Abstract Test

The Test Approach used in the $standard_name$ Abstract Test Suite includes four steps:

. Identify the test points

. Verify that API descriptions of the test points comply with the $standard_name$ standard

. Verify that the micro-services at each test point behave in accordance with the $standard_name$ standard.

. Verify that the resources returned at each test point are in accordance with the $standard_name$ standard and any referenced content standard.

Identification of test points is a new requirement with $standard_name$.  Since an API is not a Web Service, there may be RESTful endpoints advertised which are not intended to be targets of the compliance testing.  Section A.4.2 describes the process for crawling the API Description document and extracting those URLs which should be tested as well as the path(s) they should be tested with.  The concatenation of a Server URL with a path forms a test point.

Section A.4.3 describes how the test points are exercised to determine compliance with the $standard_name$ standard.

==== General Tests

===== HTTP 1.1

====== a) Test Purpose:
Validate that the $standard_name$ services advertised through the API conform with HTTP 1.1.

====== b) Pre-conditions:
none

====== c) Test Method:

. All compliance tests shall be configured to use the HTTP 1.1 protocol exclusively.  

====== d) References:
Requirement 7

===== Coordinate Reference Systems

====== a) Test Purpose:
Validate that all spatial geometries provided through a $standard_name$ service are in the CRS84 spatial reference system unless otherwise requested by the client.

====== b) Pre-conditions:
none

====== c) Test Method:

. Do not specify a coordinate reference system in any request.  All spatial data should be in the CRS84 reference system.

. Validate retrieved spatial data using the CRS84 reference system.

====== d) References:
Requirement 8

==== Retrieve the API Description

===== Landing Page Retrieval

====== a) Test Purpose:
Validate that a landing page can be retrieved from the expected location.

====== b) Pre-conditions:

* A URL to the server hosting the landing page is known.

* The test client can authenticate to the server.

* The test client has sufficient privileges to access the landing page.

====== c) Test Method:

. Issue an HTTP GET request to the URL {root}/

. Validate that a document was returned with a status code 200

. Validate the contents of the returned document using test A.4.2.2

====== d) References:
Requirement 1

===== Landing Page Validation

====== a) Test Purpose:
Validate that the landing page complies with the require structure and contents.

====== b) Pre-conditions:

* The landing page has been retrieved from the server

====== c) Test Method:

. Validate the landing page against the root.yaml schema

. Validate that the landing page includes a “service” link to API Definition

. Validate that the landing page includes a “conformance” link to the conformance class document

. Validate that the landing page includes a “data” link to the $standard_name$ contents.

====== d) References:
Requirement 2

===== OpenAPI Document Retrieval

Note: The URI for the API definition is provided through the landing page.  However, that does not mean that the API definition resides on the same server as the landing page.  Test clients should be prepared for a $standard_name$ implementation which is distributed across multiple servers.

====== a) Test Purpose:
Validate that the API Definition document can be retrieved from the expected location.

====== b) Pre-conditions:

* A URL to the server hosting the API Definition document is known.

* The test client can authenticate to the server.

* The test client has sufficient privileges to assess the API Definition document.

====== c) Test Method:

. Issue an HTTP GET request to the URL {server}/api

. Validate that a document was returned with a status code 200

. Validate the contents of the returned document using test A.4.2.4

====== d) References:
Requirements 3 and 4

===== API Definition Validation

====== a) Test Purpose:
Validate that the API Definition page complies with the require structure and contents.

====== b) Pre-conditions:

* The API Definition document has been retrieved from the server

====== c) Test Method:

. Validate the API Definition document against the OpenAPI 3.0 schema

. Identify the Test Points as described in test A.4.3

. Process the API Definition document as described in test A.4.4

====== d) References:
Requirement 4

==== Identify the Test Points

Identification of the test points is a pre-condition to performing a compliance test.  Thisprocess starts with A.4.3.1.

===== Identify Test Points:

====== a) Purpose:
To identify the test points associated with each Path in the OpenAPI document

====== b) Pre-conditions:

*   An OpenAPI document has been obtained
*   A list of URLs for the servers to be included in the compliance test has been provided
*   A list of the paths specified in the $standard_name$ specification

====== c) Method:

FOR EACH paths property in the OpenAPI document
    If the path name is one of those specified in the $standard_name$ specification
        Retrieve the Server URIs using A.4.3.2.
        FOR EACH Server URI
            Concatenate the Server URI with the path name to form a test point.
            Add that test point to the list.

====== d) References:
None

===== Identify Server URIs:

====== a) Purpose:
To identify all server URIs applicable to an OpenAPI Operation Object

====== b) Pre-conditions:

*   Server Objects from the root level of the OpenAPI document have been obtained
*   A Path Item Object has been retrieved
*   An Operation Object has been retrieved
*   The Operation Object is associated with the Path Item Object
*   A list of URLs for the servers to be included in the compliance test has been provided

====== c) Method:

1) Identify the Server Objects which are in-scope for this operation

 - IF Server Objects are defined at the Operation level, then those and only those Server Objects apply to that Operation.

 - IF Server Objects are defined at the Path Item level, then those and only those Server Objects apply to that Path Item.

 - IF Server Objects are not defined at the Operation level, then the Server Objects defined for the parent Path Item apply to that Operation.

 - IF Server Objects are not defined at the Path Item level, then the Server Objects defined for the root level apply to that Path.

 - IF no Server Objects are defined at the root level, then the default server object is assumed as described in the OpenAPI specification.

2) Process each Server Object using A.4.3.3.

3) Delete any Server URI which does not reference a server on the list of servers to test.

====== d) References:
None

===== Process Server Object:

====== a) Purpose:
To expand the contents of a Server Object into a set of absolute URIs.

====== b) Pre-conditions:

*   A Server Object has been retrieved

====== c) Method:

Processing the Server Object results in a set of absolute URIs.  This set contains all of the URIs that can be created given the URI template and variables defined in that Server Object.

. If there are no variables in the URI template, then add the URI to the return set.

. For each variable in the URI template which does not have an enumerated set of valid values:
    - generate a URI using the default value,
    - add this URI to the return set,
    - flag this URI as non-exhaustive
. For each variable in the URI template which has an enumerated set of valid values:
    - generate a URI for each value in the enumerated set,
    - add each generated URI to the return set.

. Perform this processing in an iterative manner so that there is a unique URI for all possible combinations of enumerated and default values.

. Convert all relative URIs to absolute URIs by rooting them on the URI to the server hosting the OpenAPI document.

====== d) References:
None

==== Processing the OpenAPI Document

===== Validate /api path

====== a) Test Purpose:
Validate API definition provided through the /api path it the athoritative definition of this API.  Validate that this resource exists at the expected location and that it complies with the appropirate schema. 

====== b) Pre-conditions:
* A URL to the server hosting the API definition document is known

====== c) Test Method:

. Issue an HTTP GET request to the URL {server}/api
 
. Validate that a document was returned with a status code of 200
 
. Validate the returned document against the OpenAPI 3.0 schema

====== d) References:
Requirement 4

===== Validate Conformance Operation

====== a) Test Purpose:
Validate that Conformance Operation behaves as required.

====== b) Pre-conditions:

* Path = /conformance

====== c) Test Method:

DO FOR each /conformance test point

. Issue an HTTP GET request using the test point URI

. Go to test A.4.4.3.

====== d) References:
Requirement 5

===== Validate Conformance Operation Response

====== a) Test Purpose:
Validate the Response to the Conformance Operation.

====== b) Pre-conditions:

* Path = /conformance

* A Conformance document has been retrieved

====== c) Test Method:

. Validate the retrieved document against the classes.yaml schema.

. Record all reported compliance classes and associate that list with the test point. This information will be used in latter tests.

====== d) References:
Requirement 6

===== Validate the Get Processes Operation

====== a) Test Purpose:
Validate that the Get Processes Operation behaves as required

====== b) Pre-conditions:

* Path = /processes/

====== c) Test Method:

 - Issue an HTTP GET request using the test point
URI

 - Go to test <<validate_get_processes_response>>

====== d) References:
Requirement 9

[[validate_get_processes_response]]
===== Validate Get Processes Operation Response

====== a) Test Purpose:
Validate that response to the Process Collection Operation.

====== b) Pre-conditions:

* A Process Collection document has been retrieved

====== c) Test Method:

. Validate the retrieved document against the processCollection.yaml schema.

. Validate each Process Description using test <<validate_process_description>>

====== d) References:

Requirements 10, 11, and 12

[[validate_process_description]]
===== Validate the Process Description Operation

====== a) Test Purpose:
Validate a Process Description document.

====== b) Pre-conditions:

* Path = /processes/

====== c) Test Method:

DO FOR each /processes/{processId} test point

 - Issue an HTTP GET request using the test point URI

 - Go to test <<validate_process_description_response>>

====== d) References:
Requirement 15

[[validate_process_description_response]]
===== Validate the Process Description Operation Response

====== a) Test Purpose:
Validate that response to the Process Description Operation.

====== b) Pre-conditions:

* A Process Description document has been retrieved

====== c) Test Method:

. Validate the retrieved document against the processOffering.yaml schema.

====== d) References:
Requirement 16

===== Validate the Get Jobs Operation

====== a) Test Purpose:
Validate that the Get Jobs Operation behaves as required.

====== b) Pre-conditions:

* A process id is provided by test <<validate_get_processes_response>>

* Path = /processes/{processId}/jobs

====== c) Test Method:

 - Issue an HTTP GET request using the test point URI

 - Go to test <<validate_get_jobs_response>>

====== d) References:
Requirement 17

[[validate_get_jobs_response]]
===== Validate the Get Jobs Operation Response

====== a) Test Purpose:
Validate the Get Jobs Operation Response.

====== b) Pre-conditions:

* A collection of Jobs has been retrieved

====== c) Test Method:

. Validate the structure of the response as follows:

    - For HTML use Human inspection

    - For JSON use jobCollection.yaml

====== d) References:
Requirements 24, 25, 26, 27, 28 and 29

===== Execute Operation

====== a) Test Purpose:
Validate that the Execute Operation behaves as required.

====== b) Pre-conditions:

* A process id is provided by test <<validate_get_processes_response>>

* Inputs are provided.

* Path = /processes/{processId}/jobs

====== c) Test Method:

    - Issue an HTTP POST request using the test point URI
    
    - TODO: Inputs/Execute request in body 
    
    - TODO sync/async

    - Go to test <<validate_execute_response>>

====== d) References:
Requirement 30

[[validate_execute_response]]
===== Validate the Execute Operation Response

====== a) Test Purpose:
Validate the Execute Operation Response.

====== b) Pre-conditions:

*   An Execute request has been issued to the server.

====== c) Test Method:

. Validate the structure of the response as follows:

    - For HTML use Human Inspection

    - For JSON use statusInfo.yaml

. Validate that the following links are included in the response document:

    - To itself
    
    - TODO when successful, link to result must be there
    
. Validate that all links include the rel and type link parameters.

====== d) References:
Requirements 31 and 32