== Conventions
This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this specification are denoted by the URI

http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

Permissions that appear in this document are denoted by partial URIs which are relative to the following base:

http://www.opengis.net/spec/WPS/2.0/per/service/binding/rest-json

Recommendations that appear in this document are denoted by partial URIs which are relative to the following base:

http://www.opengis.net/spec/WPS/2.0/rec/service/binding/rest-json

=== Abbreviated Terms

|=======================
|*Abbreviated Term* |*Meaning*
|CRS	| Coordinate Reference System
|GML	| Geography Markup Language
|HTTP	|Hypertext Transfer Protocol
|ISO	| International Organization for Standardization
|KVP	| Keyword Value Pair
|MIME	|Multipurpose Internet Mail Extensions
|OGC	| Open Geospatial Consortium
|URI	| Universal Resource Identifier
|URL	| Uniform Resource Locator
|WPS	| Web Processing Service
|XML	| Extensible Markup Language
|REST	| Representational State Transfer
|JSON	| JavaScript Object Notation
|=======================

=== Use of the Term "Process"

The term process is one of the most used terms both in the information and geosciences domain. If not stated otherwise, this specification uses the term process as an umbrella term for any algorithm, calculation or model that either generates new data or transforms some input data into output data as defined in section 4.1 of the WPS 2.0 standard. 

=== Namespace Conventions

|=======================
|*Prefix* |*Namespace URI*	|*Description*
|ows	| http://www.opengis.net/ows/2.0	|OWS Common 2.0 XML Schema
|xlink	| http://www.w3.org/1999/xlink	|Definitions for XLINK
|xml	| http://www.w3.org/XML/1998/namespace |	XML (required for xml:lang)
|xs	    |http://www.w3.org/2001/XMLSchema|	XML Schema
|=======================