== Conventions
This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this specification are denoted by the URI

http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

Permissions that appear in this document are denoted by partial URIs which are relative to the following base:

http://www.opengis.net/spec/WPS/2.0/per/service/binding/rest-json

Recommendations that appear in this document are denoted by partial URIs which are relative to the following base:

http://www.opengis.net/spec/WPS/2.0/rec/service/binding/rest-json

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> is used.

The following <<link-relations,registered link relation types>> are used in this document.

* **alternate**: Refers to a substitute for this context.

* **license**: Refers to a license associated with this context.

* **self**: Conveys an identifier for the link's context.

* **service-desc**: Identifies service description for the context that is primarily intended for consumption by machines.

** API definitions are considered service descriptions.

* **service-doc**: Identifies service documentation for the context that is primarily intended for human consumption.

In addition the following link relation types are used for which no applicable registered link relation type could be identified.

* **conformance**: Refers to a resource that identifies the specifications that the link's context conforms to.

* **exceptions**: The target URI points to exceptions of a failed process.

* **execute**: The target URI points to the execution endpoint of a process.

* **process-description**: The target URI points to a specific process description.

* **processes**: The target URI points to the collection of processes the API offers.

* **results**: The target URI points to the results of a process.

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API. 

=== Abbreviated Terms

|=======================
|*Abbreviated Term* |*Meaning*
|API	| Application Programming Interface
|CRS	| Coordinate Reference System
|GML	| Geography Markup Language
|HTTP	| Hypertext Transfer Protocol
|ISO	| International Organization for Standardization
|KVP	| Keyword Value Pair
|MIME	| Multipurpose Internet Mail Extensions
|OGC	| Open Geospatial Consortium
|URI	| Universal Resource Identifier
|URL	| Uniform Resource Locator
|WPS	| Web Processing Service
|XML	| Extensible Markup Language
|REST	| Representational State Transfer
|JSON	| JavaScript Object Notation
|=======================

=== Use of the Term "Process"

The term process is one of the most used terms both in the information and geosciences domain. If not stated otherwise, this specification uses the term process as an umbrella term for any algorithm, calculation or model that either generates new data or transforms some input data into output data as defined in section 4.1 of the WPS 2.0 standard. 
