[[ats_kvp-execute_input-by-reference]]

[abstract_test]
====
[%metadata]
identifier:: /conf/kvp-execute/input-by-reference
target:: /req/kvp-execute/input-by-reference
test-purpose:: Verify that passing process inputs by reference for KVP-encoded execute request are correctly handled.
test-method::
+
--
1. Get a list of processes as per test <<ats_core_process-list-op,/conf/core/process-list-op>>.

2. Retrieve the description of each process according to test <<ats_core_process-description-op,/conf/core/process-description-op>>.

3. Inspect the input definitions of each process and identify a process with an input that supports passing values by reference.  The absence of the `valuePassing` parameter in the inputs definition indicates that values passed by reference is supported.  If the `valuePassing` parameter is present then it must include the value `byReference` to indicate the value passing by reference is supported.

4. Compose a KVP-encoded execute request encoding input values by reference as per <<req_kvp-execute_input-by-reference,/req/kvp-execute/input-by-reference>>.

5. Execute the request using the HTTP `GET` method.

6. Verify that the response of the process is the expected response (see tests: <<req_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<req_core_process-execute-success-async-outputs,/req/core/process-execute-success-async-outputs>>, <<req_core_process-execute-success-async-outputs-empty,/req/core/process-execute-success-async-outputs-empty>>, <<req_core_process-execute-success-async-outputs-omitted,/req/core/process-execute-success-async-outputs-omitted>>, <<req_core_process-execute-success-sync-empty-outputs,/req/core/process-execute-success-sync-empty-outputs>>, <<req_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<req_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<req_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>).
--
====
