[[ats_kvp-execute_f-response]]

[abstract_test]
====
[%metadata]
identifier:: /conf/kvp-execute/f-response
target:: /req/kvp-execute/f-response
test-purpose:: Validate that the `response[f]` query parameter is processed correctly.
test-method::
+
--
1. Get a list of processes as per test <<ats_core_process-list-op,/conf/core/process-list-op>>.

2. Retrieve the description of each process according to test <<ats_core_process-description-op,/conf/core/process-description-op>>.

3. Inspect the input definitions of each process and identify a process that has at least one input with more that one defined output format.

4. Compose a KVP-encoded execute request as per test <<req_kvp-execute_process-execute-op,/req/kvp-execute/process-execute-op>>.

5. Append the `response[f]` parameter requesting a supported output format identified in Step #3.

6. Execute each request using the HTTP `GET` method.

7. Verify that the response of the process is the expected response (see tests: <<req_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<req_core_process-execute-success-async-outputs,/req/core/process-execute-success-async-outputs>>, <<req_core_process-execute-success-async-outputs-empty,/req/core/process-execute-success-async-outputs-empty>>, <<req_core_process-execute-success-async-outputs-omitted,/req/core/process-execute-success-async-outputs-omitted>>, <<req_core_process-execute-success-sync-empty-outputs,/req/core/process-execute-success-sync-empty-outputs>>, <<req_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<req_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<req_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>).

8. Verify that the response format corresponds to the format requested via the `response[f]` parameter.
--
====
