[[ats_kvp-execute_bbox-crs-input-value]]

[abstract_test]
====
[%metadata]
identifier:: /conf/kvp-execute/bbox-crs-input-value
target:: /req/kvp-execute/bbox-crs-input-value
test-purpose:: Verify that bbox-valued process inputs for KVP-encoded execute request with CRSs other than http://www.opengis.net/def/crs/OGC/1.3/CRS84 or http://www.opengis.net/def/crs/OGC/0/CRS84h are correctly handled.
test-method::
+
--
1. Get a list of processes as per test <<ats_core_process-list-op,/conf/core/process-list-op>>.

2. Retrieve the description of each process according to test <<ats_core_process-description-op,/conf/core/process-description-op>>.

3. Inspect the input definitions of each process and identify the processes that have at least one bounding-box-typed input.

4. Identify that subset of the processes identified in Step #2 that support CRSs other than http://www.opengis.net/def/crs/OGC/1.3/CRS84 or http://www.opengis.net/def/crs/OGC/0/CRS84h.

5. Compose a KVP-encoded execute request encoding the bbox-typed input(s) according to <<req_kvp-execute_bbox-input-value,/req/kvp-execute/bbox-input-value>> and encoding the CRS according to <<req_kvp-execute_bbox-crs-input-value,/req/kvp-execute/bbox-crs-input-value>>.

6. Execute the request using the HTTP `GET` method.

7. Verify that the response of the process is the expected response (see test: <<req_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<req_core_process-execute-success-async-outputs,/req/core/process-execute-success-async-outputs>>, <<req_core_process-execute-success-async-outputs-empty,/req/core/process-execute-success-async-outputs-empty>>, <<req_core_process-execute-success-async-outputs-omitted,/req/core/process-execute-success-async-outputs-omitted>>, <<req_core_process-execute-success-sync-empty-outputs,/req/core/process-execute-success-sync-empty-outputs>>, <<req_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<req_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<req_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>).
--
====
