oneOf:
  - $ref: link.yaml
  - type: object
    properties:
      title:
        type: string
      multipleOf:
        type: number
        minimum: 0
        exclusiveMinimum: true
      maximum:
        type: number
      exclusiveMaximum:
        type: boolean
        default: false
      minimum:
        type: number
      exclusiveMinimum:
        type: boolean
        default: false
      maxLength:
        type: integer
        minimum: 0
      minLength:
        type: integer
        minimum: 0
        default: 0
      pattern:
        type: string
        format: regex
      maxItems:
        type: integer
        minimum: 0
      minItems:
        type: integer
        minimum: 0
        default: 0
      uniqueItems:
        type: boolean
        default: false
      maxProperties:
        type: integer
        minimum: 0
      minProperties:
        type: integer
        minimum: 0
        default: 0
      required:
        type: array
        items:
          type: string
        minItems: 1
        uniqueItems: true
      enum:
        type: array
        items: {}
        minItems: 1
        uniqueItems: false
      type:
        type: string
        enum:
        - array
        - boolean
        - integer
        - number
        - object
        - string
      not:
        "$ref": "schema.yaml"
      allOf:
        type: array
        items:
          "$ref": "schema.yaml"
      oneOf:
        type: array
        items:
          "$ref": "schema.yaml"
      anyOf:
        type: array
        items:
          "$ref": "schema.yaml"
      items:
        "$ref": "schema.yaml"
      properties:
        type: object
        additionalProperties:
          "$ref": "schema.yaml"
      additionalProperties:
        oneOf:
          - "$ref": "schema.yaml"
      description:
        type: string
      format:
        type: string
      default: {}
      nullable:
        type: boolean
        default: false
      readOnly:
        type: boolean
        default: false
      writeOnly:
        type: boolean
        default: false
      example: {}
      deprecated:
        type: boolean
        default: false
      contentMediaType:
        type: string
      contentEncoding:
        type: string
      contentSchema:
        $ref: "schema.yaml"
    additionalProperties: false
