== Requirements Class "Job Management"

[[job-management]]
=== Overview

include::../requirements/requirements_class_job-management.adoc[]

A server that implements the Job Management Requirements Class provides the ability to
create, update and start jobs.

The HTTP POST method on the `/jobs` path is used on to create new jobs.

The HTTP PATCH method on the `/jobs/{jobId}` is used to update the definition of a previously created jobs that are accessible via the Processes API endpoint.

Finally, the HTTP POST method on the `/job/{jobId}/results` is used to start a job.

Creating or updating a job requires that a formal description of the new or
updated jobs be provided by the client.  This Standar does not
mandate that a specific jobs schema be used.
However, this extension defines the following conformance
classe:

 * <<rc_ogcapi-processes,OGC API - Processes - Wrokflow Execute Request>>, that enables support for OGC API - Processes - Part 3: Wofklows for jobs definitions.
 * <<rc_openeo,OpenEO Process Graph>>, that enables support for OpenEO-encoded jobs definitions.
 

[[job-management-http_status_codes]]
==== HTTP status codes

Clients implementing the Processes API Part 4 should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this Standard. Status codes 200, 201 and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API implementation. Support for these status codes is strongly encouraged for both client and server implementations.

[[status_codes]]
.Typical HTTP status codes
[cols="15,85",options="header"]
|===
|Status code |Description
|`200` |A successful request.
|`201` |The server has successfully completed the operation and a new resource has been created.
|`202` |The request was accepted for processing, but the processing was not completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
|`204` |A successful request with no additional content to send in the response.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to execute the request. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but that the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`412` |The status code indicates that one or more conditions given in the request header fields evaluated to false when tested by the server.
|`413` |The server is refusing to process the request because the request content is larger than the server is willing or able to process.
|`415` |The server is refusing to service the request because the content is in a format not supported by this method on the target resource.
|`422` |The server understands the content type of the request content and the syntax of the request content is correct, but was unable to process the contained instructions. For example, the submitted resource does not meet a semantic constraint, e.g. a mandatory property is missing.
|`500` |An internal error occurred in the server.
|===

NOTE: Status code `422` is not yet an official HTTP status code, but is expected to be added by the https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-422-unprocessable-content[draft IETF RFC "HTTP Semantics"].

More specific guidance is provided for each resource, where applicable.

include::../recommendations/job-management/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API imeplementation instance. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document be limited to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[cross_origin]]
==== Cross-origin requests

See <<OAFeat-1,OGC API - Features - Part 1: Core>>, section link:http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#cross_origin[Support for cross-origin requests], about the importance of supporting cross-origin requests, typically via link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)].



[[job-management-create]]
=== Creating a new job

==== Sequence diagram

The following diagram illustrates the sequence diagram for deploying
a new process to the API:


```
Client                                                        Server
  |                                                             |
  |  POST /jobs   HTTP/1.1                                      |
  |  Content-Type: application/json                             |
  |                                                             |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 201 Created                                       |
  |  Location: /jobs/{jobId}                                    |
  |<------------------------------------------------------------|
```


==== Operation

include::../requirements/job-management/create/REQ_post-op.adoc[]

==== Request body

===== Overview

include::../requirements/job-management/create/REQ_body.adoc[]

include::../recommendations/job-management/create/PER_body.adoc[]

include::../requirements/job-management/create/REQ_content-type.adoc[]

See https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.5[section 3.1.1.5 of RFC 7231] for details.

include::../recommendations/job-management/create/PER_content-schema.adoc[]

===== OGC API - Processes - Workflow Execute Request body

include::../recommendations/job-management/create/REC_body-ogcapi-processes.adoc[]

===== OpenEO Process Graph body

include::../recommendations/job-management/create/REC_body-openeo.adoc[]


==== Response

include::../requirements/job-management/create/REQ_response-jobid.adoc[]

include::../requirements/job-management/create/REQ_response-success.adoc[]

include::../requirements/job-management/create/REQ_response-body.adoc[]

==== Exceptions

See <<job-management-http_status_codes>> for general guidance.

If the request body's media type is not supported by the server, see requirement /req/deploy-replace-undeploy/deploy/unsupported-media-type from <<OAProc-2>>.

include::../requirements/job-management/create/REQ_unsupported-schema.adoc[]


[[job-management-update]]
=== Updating an existing job

==== Sequence diagram

The following diagram illustrates the sequence diagram for updating a
previously created job.  The identifier of the job does not change.

NOTE: The new job definition replaces the old job definition. Version control is not discussed in this Standard.

```
Client                                                        Server
  |                                                             |
  |  PATCH /jobs/{jobId}   HTTP/1.1                             |
  |  Content-Type: application/json                             |
  |                                                             |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 200 OK                                            |
  |<------------------------------------------------------------|
```

==== Operation

include::../requirements/job-management/update/REQ_patch-op.adoc[]

==== Request body

==== Overview

include::../requirements/job-management/update/REQ_body.adoc[]

include::../recommendations/job-management/update/PER_body.adoc[]

include::../requirements/job-management/update/REQ_content-type.adoc[]

include::../recommendations/job-management/update/PER_content-schema.adoc[]

===== OGC API - Processes - Workflow Execute Request

include::../recommendations/job-management/update/REC_body-ogcapi-processes.adoc[]

===== OpenEO Process Graph

include::../recommendations/job-management/update/REC_body-openeo.adoc[]

==== Response

include::../requirements/job-management/update/REQ_response.adoc[]

The status code depends on the server. If the server has replaced the job, the response is either `200` (if the response includes additional content) or `204` (if the response has no additional content).

==== Exceptions

See <<job-management-http_status_codes>> for general guidance.

If the request body's media type is not supported by the server, see requirement /req/deploy-replace-undeploy/deploy/unsupported-media-type from <<OAProc-2>>.

If the job with the specified identifier does not exist on the server, see requirement /req/core/job-exception-no-such-job from <<OAProc-1>>.

include::../requirements/job-management/update/REQ_response-locked.adoc[]

[[job-management-start]]
=== Staring a job

==== Sequence diagram

The following diagram illustrates the sequence diagram for starting 
the execution of a previously created jobs.


```
Client                                                        Server
  |                                                             |
  |  POST /jobs/{jobId}/results   HTTP/1.1                      |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 200 OK                                            |
  |<------------------------------------------------------------|
```

==== Operation

include::../requirements/job-management/start/REQ_post-op.adoc[]

==== Response

include::../requirements/job-management/start/REQ_response.adoc[]

==== Exceptions

See <<job-management-http_status_codes,HTTP status codes>> for general guidance.

If the job with the specified identifier does not exist on the server, see requirement /req/core/job-exception-no-such-job from <<OAProc-1>>.

If the job with the specified identifier is locked, see requirement /req/job-management/update/response-locked from <<job-management-update>>.


[[job-management-definition]]
=== Job definition

For every job, it is possible to retrieve its original definition. It corresponds to the request's body used to create or update the jobs.

==== Operation

include::../requirements/job-management/definition/REQ_get-op.adoc[]

==== Response

===== Overview

include::../requirements/job-management/definition/REQ_response-success.adoc[]

include::../requirements/job-management/definition/REQ_response-body.adoc[]

==== Exceptions

See <<deploy-replace-undeploy-http_status_codes,HTTP status codes>> for general guidance.

If the job with the specified identifier does not exist on the server, see requirement /req/core/job-exception-no-such-job from <<OAProc-1>>.

