[[ats_job-list]]

[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list
subject:: <<rc_core,http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list>>
classification:: Target Type:Web API
conformance-test:: /conf/job-list/datetime-definition
conformance-test:: /conf/job-list/datetime-response
conformance-test:: /conf/job-list/duration-definition
conformance-test:: /conf/job-list/duration-response
conformance-test:: /conf/job-list/job-list-op
conformance-test:: /conf/job-list/job-list-success
conformance-test:: /conf/job-list/limit-definition
conformance-test:: /conf/job-list/limit-response
conformance-test:: /conf/job-list/links
conformance-test:: /conf/job-list/processID-definition
conformance-test:: /conf/job-list/processID-mandatory
conformance-test:: /conf/job-list/processID-response
conformance-test:: /conf/job-list/status-definition
conformance-test:: /conf/job-list/status-response
conformance-test:: /conf/job-list/type-definition
conformance-test:: /conf/job-list/type-response
====

include::job-list/ATS_op.adoc[]

include::job-list/ATS_type-def.adoc[]

include::job-list/ATS_type-response.adoc[]

include::job-list/ATS_processid-mandatory.adoc[]

include::job-list/ATS_processid-def.adoc[]

include::job-list/ATS_processid-response.adoc[]

include::job-list/ATS_status-def.adoc[]

include::job-list/ATS_status-response.adoc[]

include::job-list/ATS_datetime-def.adoc[]

include::job-list/ATS_datetime-response.adoc[]

include::job-list/ATS_duration-def.adoc[]

include::job-list/ATS_duration-response.adoc[]

include::job-list/ATS_limit-def.adoc[]

include::job-list/ATS_limit-response.adoc[]

include::job-list/ATS_links.adoc[]


NOTE: A job list may be retrieved in one of two formats. The following table identifies the applicable schema document for each format and the test to be used to validate the against that schema. All supported formats should be exercised.

[[job-list-schema]]
.Schema and Tests for Job List Content
[cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/jobList.yaml[jobList.yaml] |<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/jobList.yaml[jobList.yaml] |<<ats_json_content,/conf/json/content>>
|===

include::job-list/ATS_success.adoc[]
