[[ats_core]]
[conformance_class]
.Core
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-processes-1/2.0/conf/core
subject:: <<rc_core,http://www.opengis.net/spec/ogcapi-processes-1/2.0/req/core>>
classification:: Target Type:Web API
conformance-test:: /conf/core/test-process
conformance-test:: /conf/core/landingpage-op
conformance-test:: /conf/core/landingpage-success
conformance-test:: /conf/core/api-definition-op
conformance-test:: /conf/core/api-definition-success
conformance-test:: /conf/core/conformance-op
conformance-test:: /conf/core/conformance-success
conformance-test:: /conf/core/http
conformance-test:: /conf/core/process-list-op
conformance-test:: /conf/core/process-list-limit-definition
conformance-test:: /conf/core/process-list-limit-response
conformance-test:: /conf/core/process-list-success
conformance-test:: /conf/core/process-list-links
conformance-test:: /conf/core/process-summary-links
conformance-test:: /conf/core/process-description
conformance-test:: /conf/core/process-description-success
conformance-test:: /conf/core/process-exception-no-such-process
conformance-test:: /conf/core/process-execute-op
conformance-test:: /conf/core/process-execute-request
conformance-test:: /conf/core/process-execute-default-execution-mode
conformance-test:: /conf/core/process-execute-auto-execution-mode
conformance-test:: /conf/core/process-execute-input-array
conformance-test:: /conf/core/process-execute-input-inline-object
conformance-test:: /conf/core/process-execute-input-inline-multiple-types
conformance-test:: /conf/core/process-execute-input-inline-binary
conformance-test:: /conf/core/process-execute-input-inline-bbox
conformance-test:: /conf/core/process-execute-input-validation
conformance-test:: /conf/core/process-execute-omitted-outputs
conformance-test:: /conf/core/process-execute-empty-outputs
conformance-test:: /conf/core/process-execute-sync-one
conformance-test:: /conf/core/process-execute-sync-one-default-content
conformance-test:: /conf/core/process-execute-sync-many-json
conformance-test:: /conf/core/process-execute-success-async-outputs-omitted
conformance-test:: /conf/core/process-execute-success-async-outputs-empty
conformance-test:: /conf/core/job-results-success-sync
conformance-test:: /conf/core/process-execute-success-async
conformance-test:: /conf/core/process-execute-success-async-outputs
conformance-test:: /conf/core/process-execute-success-sync-empty-outputs
conformance-test:: /conf/core/process-execute-success-sync-outputs-omitted
conformance-test:: /conf/core/job-op
conformance-test:: /conf/core/job-success
conformance-test:: /conf/core/job-exception-no-such-job
conformance-test:: /conf/core/job-results-op
conformance-test:: /conf/core/job-results-param-outputs
conformance-test:: /conf/core/job-results-param-outputs-response
conformance-test:: /conf/core/job-result-op
conformance-test:: /conf/core/job-results-async-one
conformance-test:: /conf/core/job-results-async-many
conformance-test:: /conf/core/job-results-exception-invalid-query-parameter-value
conformance-test:: /conf/core/job-results-exception-no-such-output
conformance-test:: /conf/core/job-results-exception-no-such-job
conformance-test:: /conf/core/job-results-exception-results-not-ready
conformance-test:: /conf/core/job-results-exception_results-not-available
conformance-test:: /conf/core/job-results-failed
====

=== Testable process

include::core/ATS_test-process.adoc[]

=== Retrieve the API landing page

include::core/ATS_landingpage-op.adoc[]

include::core/ATS_landingpage-success.adoc[]

=== Retrieve an API definition

include::core/ATS_api-definition-op.adoc[]

include::core/ATS_api-definition-success.adoc[]

=== Declaration of conformance classes

include::core/ATS_conformance-op.adoc[]

include::core/ATS_conformance-success.adoc[]

=== Use of HTTP 1.1

include::core/ATS_http.adoc[]

=== Retrieve a process list

include::core/ATS_process-list-op.adoc[]

include::core/ATS_process-list-limit-def.adoc[]

include::core/ATS_process-list-limit-response.adoc[]

include::core/ATS_process-list-success.adoc[]

include::core/ATS_process-list-links.adoc[]

include::core/ATS_process-summary-links.adoc[]

=== Retrieve a process description

include::core/ATS_process-description-op.adoc[]

include::core/ATS_process-description-success.adoc[]

=== Process exception

include::core/ATS_process-exception-no-such-process.adoc[]

=== Process execution /processes/{processID}/execution

include::core/ATS_process-execute-op.adoc[]

include::core/ATS_process-execute-request.adoc[]

include::core/ATS_process-execute-default-execution-mode.adoc[]

include::core/ATS_process-execute-auto-execution-mode.adoc[]

include::core/ATS_process-execute-input-array.adoc[]

include::core/ATS_process-execute-input-inline-object.adoc[]

include::core/ATS_process-execute-input-inline-multiple-types.adoc[]

include::core/ATS_process-execute-input-inline-binary.adoc[]

include::core/ATS_process-execute-input-inline-bbox.adoc[]

include::core/ATS_process-execute-input-validation.adoc[]

include::core/ATS_process-execute-outputs-omitted.adoc[]

include::core/ATS_process-execute-outputs-empty.adoc[]

include::core/ATS_process-execute-success-sync-one.adoc[]

include::core/ATS_process-execute-success-sync-one-default-content.adoc[]

include::core/ATS_process-execute-success-sync-many-json.adoc[]

include::core/ATS_process-execute-success-sync-outputs-omitted.adoc[]

include::core/ATS_process-execute-success-sync-outputs-empty.adoc[]

include::core/ATS_job-results-success-sync.adoc[]

include::core/ATS_process-execute-success-async.adoc[]

include::core/ATS_process-execute-success-async-outputs.adoc[]

include::core/ATS_process-execute-success-async-outputs-empty.adoc[]

include::core/ATS_process-execute-success-async-outputs-omitted.adoc[]

=== Jobs

==== Job status /jobs/{jobID}

include::core/ATS_job-op.adoc[]

include::core/ATS_job-success.adoc[]

include::core/ATS_job-exception-no-such-job.adoc[]

==== Retrieve job results

include::core/ATS_job-results-op.adoc[]

include::core/ATS_job-results-param-outputs.adoc[]

include::core/ATS_job-results-param-outputs-response.adoc[]

include::core/ATS_job-results-profile.adoc[]

include::core/ATS_job-result-op.adoc[]

include::core/ATS_job-results-success-async-one.adoc[]

include::core/ATS_job-results-success-async-many.adoc[]

include::core/ATS_job-results-exception-invalid-query-parameter-value.adoc[]

include::core/ATS_job-results-exception-no-such-output.adoc[]

include::core/ATS_job-results-exception-no-such-job.adoc[]

include::core/ATS_job-results-exception-results-not-ready.adoc[]

include::core/ATS_job-results-exception-results-not-available.adoc[]

include::core/ATS_job-results-failed.adoc[]
