
== Requirements Class "Transactions"

[[transactions-overview]]
=== Overview

include::requirements/requirements_class_transactions.adoc[]

A server that implements this conformance class provides the ability to
dynamically add, replace and remove processes from a deployed processes API.

The HTTP POST method is used to add new processes to the API.

The HTTP PUT method is used to update the definition of a previously, dynamically added processes that is accessible via the API.

Finally, the HTTP DELETE method is used to remove  a previously, dynamically added process that is accessible via the API.

Adding or updating a process requires that a formal description of the process
to be added or changed be provided by the client.  This extension does not
mandate that a specific processes description language or vocabulary be used.
However, in order to promote interoperability, this extension defines a
conformance class, <<rc_ogcapppkg,OGC Application Package>>, that defines a
formal process description language encoded using JSON.  It is recommended
that all implementations of this extension support the `OGC Application Package`.

[[transactions-http_status_codes]]
==== HTTP status codes

API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 201 and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[[status_codes]]
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
|===
|Status code |Description
|`200` |A successful request.
|`201` |The server has been fulfilled the operation and a new resource has been created.
|`204` |A successful request with no expectation of content in the body.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`409` |Conflict.  For example, the processes already exists.
|`500` |An internal error occurred in the server.
|===

More specific guidance is provided for each resource, where applicable.

include::recommendations/transactions/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[transactions-insert]]
=== Adding a new processes to the API (deployProcess)

==== Sequence diagram

The following diagram illustrates the sequence diagram for dynamically deploying
a new process to the API:

....
   Client                                                        Server
     |                                                             |
     |  POST /processes   HTTP/1.1                                 |
     |  Content-Type: application/ogcapppkg+json                   |
     |                                                             |
     |  ... Body contains a formal description of the process to   |
     |      add (e.g. OGC Application Package) ...                 |
     |------------------------------------------------------------>|
     |                                                             |
     |  HTTP/1.1 201 Created                                       |
     |  Location: /processes/{processId}                           |
     |<------------------------------------------------------------|
....

==== Operation

include::requirements/transactions/insert/REQ_post-op.adoc[]

==== Request body

===== Overview

include::requirements/transactions/insert/REQ_body.adoc[]

include::recommendations/transactions/insert/PER_body.adoc[]

include::requirements/transactions/insert/REQ_content-type.adoc[]

===== OGC Application Package body

include::recommendations/transactions/insert/REC_body-ogcapppkg.adoc[]

==== Response

include::requirements/transactions/insert/REQ_response-pid.adoc[]

include::requirements/transactions/insert/REQ_response.adoc[]

include::requirements/transactions/insert/REQ_response-body.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

[[transactions-update-put]]
=== Updating an existing processes (modifyProcess)

==== Sequence diagram

The following diagram illustrates the sequence diagram for updating a previously
deployed processes.

....
   Client                                                        Server
     |                                                             |
     |  PUT /processes/{processId}   HTTP/1.1                      |
     |  Content-Type: application/ogcapppkg+json                   |
     |                                                             |
     |  ... Body contains a formal description of the process to   |
     |      replace the existing process (e.g. OGC Application     |
     |      Package) ...                                           |
     |------------------------------------------------------------>|
     |                                                             |
     |  HTTP/1.1 204 OK                                            |
     |<------------------------------------------------------------|
....

==== Operation

include::requirements/transactions/update/REQ_put-op.adoc[]

==== Request body

==== Overview

include::requirements/transactions/update/REQ_body.adoc[]

include::recommendations/transactions/update/PER_body.adoc[]

include::requirements/transactions/update/REQ_content-type.adoc[]

===== OGC Application Package body

include::recommendations/transactions/update/REC_body-ogcapppkg.adoc[]

==== Response

include::requirements/transactions/update/REQ_response.adoc[]

==== Exceptions

See also <<http_status_codes,HTTP status codes>>.

[[transactions-delete]]
=== Removing a process (undeployProcess)

==== Sequence diagram

The following diagram illustrates the sequence diagram for removing a previously
deployed process.

....
   Client                                                        Server
     |                                                             |
     |  DELETE /processes/{processId}   HTTP/1.1                   |
     |------------------------------------------------------------>|
     |                                                             |
     |  HTTP/1.1 204 OK                                            |
     |<------------------------------------------------------------|
....

==== Operation

include::requirements/transactions/delete/REQ_delete-op.adoc[]

==== Response

include::requirements/transactions/delete/REQ_response.adoc[]

==== Exceptions

See <<transactions-http_status_codes,HTTP status codes>>.

=== Static processes

NOTE: I am not quite sure if we need to distinguish between processes that may be already part of a deployed OGC processes API, which I call static processes, and processes that are dynamically added via the API.  For example the CubeWerx processes API comes with a set of built-in processes that cannot be manipulated via the transaction API.  So, I include this section here for discussion.

This extension recognizes that an OGC web processing API may be deployed with
a set of built-in processes that are static and cannot be removed or modified
via the transaction API.  In an API Description Document of the API (e.g.
OpenAPI), such process paths would not include support for the HTTP POST,
PUT or DELETE methods.

However, in order to make it clear which processes in a collection (accessible
via the `/processes` path) are built-in and which have been dynamically
deployed, the processes collection schema is modified to add a flag indicating
this aspect of a process.

include::requirements/transactions/static/REQ_indicator.adoc[]

The following schema fragment extends the process summary accessible via the
`/processes` path to add the `isStatic` property.

[source,yaml]
----
allOf:
  - $ref: "descriptionType.yaml"
  - type: object
    required:
      - id
      - version
    properties:
      id:
        type: string
      version:
        type: string
      isStatic:
         type: boolean
         default: false
      jobControlOptions:
        type: array
        items:
          $ref: "jobControlOptions.yaml"
      outputTransmission:
        type: array
        items:
          $ref: "transmissionMode.yaml"
      links:
        type: array
        items:
          $ref: "link.yaml"
----
