
== Conformance

This standard defines two requirements / conformance class.

The standardization target is "Web APIs".

The main requirements class is:

* <<rc_transactions>>.

This class specifies requirements that all Web APIs have to implement.

The `Transactions` class does not mandate a specific encoding or format for
the formal definition of a process.  However, this extension defines the
following conformance class:

*  <<rc_ogcapppkg>>

for this purpose.  The `OGC Application Package` class defines the schema of a
document that formally defines the inputs, outputs and other necessary metadata
about a process that is to be dynamically deployed through the API.

This encoding is not mandatory and an implementation of this extension may choose to implement some other process description instead.  That said, the `Transactions` conformance class includes recommendations to support the `OGC Application Package`.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.
