[[rec_core_job-status]]
[recommendation]
====
[%metadata]
identifier:: /rec/core/job-status
label:: /rec/core/job-status

[.component,class=part]
--
Servers SHOULD, via the `title`, `description`, `keywords` and `metadata` fields, include descriptive metadata about the job.
--

[.component,class=part]
--
Servers SHOULD set the value of the `processID` field if it is known.
--

[.component,class=part]
--
Servers SHOULD set the value of the `created` field when a job has been accepted and queued for execution.
--

[.component,class=part]
--
Servers SHOULD set the value of the `started` field when a job begins execution and is consuming compute resources.
--

[.component,class=part]
--
Servers SHOULD set the value of the `finished` field when the execution of a job has completed, and the process is no longer consuming compute resources.
--

[.component,class=part]
--
Whenever the `status` field of the job changes, servers SHOULD revise the value of the `updated` field.
--

[.component,class=part]
--
Servers SHOULD, if the information can be determined, set the value of the `progress` field indicating how much of the job has been completed.
--
====
