[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

=== Conformance Class Core

include::abstract_tests/ATS_class_core.adoc[]

=== Conformance Class JSON

include::abstract_tests/ATS_class_json.adoc[]

=== Conformance Class Job collection

include::abstract_tests/ATS_class_job-collection.adoc[]

=== Conformance Class Callback

include::abstract_tests/ATS_class_callback.adoc[]

=== Conformance Class HTML

include::abstract_tests/ATS_class_html.adoc[]

=== Conformance Class OpenAPI 3.0

include::abstract_tests/ATS_class_oas30.adoc[]


=== Overview

Compliance testing for OGC API - Processes and similar standards must answer three questions:

.  Are the capabilities advertised through the API Description compliant with the standard?

.  Does the API implement those capabilities as advertised?

.  Do the resources returned by the micro-services meet the structure and content requirements of the standard?

Further complicating the issue, an API may expose resources in addition to those defined by the standard.  A test engine must be able to traverse the API description document, identify test points, and ignore resource paths which are not to be tested.  The process for identifying test points is provided in Section A.4.3.

=== Conventions

The following conventions apply to this Abstract Test Suite:

==== Path Templates

Path templates are used throughout these test suites.  Path templating refers to the usage of curly braces “{}” to mark a section of a URL path that can be replaced using path parameters.  The terms used to describe portions of these templates are based on the URL syntax described in RFC 3986.

*  scheme: http | https

*  authority: DNS name of the server with optional port number

*  path: The slash delimited identifier for a resource on the server

*  query: query parameters following the "?" character

*  fragment: identifies an element within the resource. Preceded by the "#" character

==== API Description Document

The OGC API - Processes standard does not mandate a standard format for the API Description Document.  However, some form of standard is needed if tests are to be accurately described and implemented.  Therefore, this Abstract Test Suite asserts that the API Description document is compliant with OpenAPI 3.0.  This Test Suite will be updated if and when an alternative is commonly adopted.

==== Resource Encodings

The OGC API - Processes standard does not mandate a standard encoding for resources returned by the API. Yet a compliance test requires some minimal level of expected behavior. Therefore, this Abstract Test Suite asserts that the API returns resources encoded in HTML and GeoJSON. Since no compliance test suite exists for these encodings at this time, the resources shall be presented to the test operator for human inspection.  

==== Processing Security Objects

OpenAPI does not provide a standard way to associate a security requirement with a single server URI.  Therefore, OGC API - Processes compliance tests will have to make that association through the runtime challenge-response transaction.  At this time the role of the Security Objects should be considered advisory.

Security Requirements can be defined at both the OpenAPI root level and at the Operation Object level. The following rules should be followed to understand the scope of a Security Requirement:

* The Security Requirements defined at the root level are the default requirements for all operations and servers.

* If Security Requirements are defined at the Operation level, then those Requirements (and not the ones defined at the OpenAPI level) shall be used with that operation.

* An empty set of Security Requirements at the Operation level indicates that there are no security requirements for that operation.

Note: this allows operations to opt-out of security requirements defined at the OpenAPI level.

==== Parameters

The following observations apply for OGC API - Processes parameters:

. OGC API - Processes does not use cookies.

. Query parameters follow common Web practice

. Header parameters are restricted to custom headers

. For path parameters, the name of the parameter must match the name of the variable in the path template in the path object

Parameters are defined at the Path Item and Operation level.  Parameters defined at the Path Item level must apply to all operations under that Path item. These parameters may be modified at the Operation level but they may not be removed.

==== Testable Paths

A testable path is a path which corresponds to one of the paths defined in the OGC API - Processes specification. There are three alternatives for making this determination:

. The path URI matches – this is the simplest approach but may be subject to error

. Use mandatory tags in the tags field of the Operation Object

. Use standardized operation ids for the operationId field of the Operation Object

A testable path is validated against the rules for that path.  At a minimum that includes:

. Building a list of all parameters which are defined in the standard

. Validate that the mandatory parameters are present and required

. Validate type, format, etc. for each parameter in the list.

. Validate that there are no mandatory parameters which are not on the list.

=== Requirements Trace Matrix

TODO update

[width="100%"]
|====================
| *Requirement 1:* API Landing Page Operation +
  The server SHALL support the HTTP GET operation at the path /. +
  Tests: A.4.2.1
| *Requirement 2:* API Landing Page Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema root.yaml and include at least links to the following resources: +
 - /api (relation type 'service') +
 - /conformance (relation type 'conformance') +
 - /collections (relation type 'data') +
Tests: A.4.2.2 +
| *Requirement 3:* API Definition Operation +
The server SHALL support the HTTP GET operation at the path /api. +
Tests: A.4.2.3 +
| *Requirement 4:* API Definition Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The server SHALL return an API definition document. +
Tests: A.4.2.3, A.4.2.4, A.4.4.1 +
| *Requirement 5:* Conformance Class Operation +
The server SHALL support the HTTP GET operation at the path /conformance. +
Tests: A.4.4.2 +
| *Requirement 6:* Conformance Class Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema req-classes.yaml and list all OGC API - Processes requirements classes that the server conforms to. +
Tests: A.4.4.3 +
| *Requirement 7:* HTTP 1.1 +
The server SHALL conform to HTTP 1.1. +
If the server supports HTTPS, the server SHALL also conform to HTTP over TLS. +
Tests: A.4.1.1 +
|====================

=== Abstract Test

The Test Approach used in the OGC API - Processes Abstract Test Suite includes four steps:

. Identify the test points

. Verify that API descriptions of the test points comply with the OGC API - Processes standard

. Verify that the micro-services at each test point behave in accordance with the OGC API - Processes standard.

. Verify that the resources returned at each test point are in accordance with the OGC API - Processes standard and any referenced content standard.

Identification of test points is a new requirement with $standard_name$.  Since an API is not a Web Service, there may be RESTful endpoints advertised which are not intended to be targets of the compliance testing.  Section A.4.2 describes the process for crawling the API Description document and extracting those URLs which should be tested as well as the path(s) they should be tested with.  The concatenation of a Server URL with a path forms a test point.

Section A.4.3 describes how the test points are exercised to determine compliance with the OGC API - Processes standard.

