[[ogc_process_description]]
== Requirements Class "OGC Process Description"

The following section describes the `OGC Process Description` requirements
class.

=== Overview

include::requirements/requirements_class_ogc-process-description.adoc[]

The OGC process description is an information model that may be used to specify the interface of a process.  This model is an evolution of the process description model originally defined in the http://docs.opengeospatial.org/is/14-065/14-065.html[OGC WPS 2.0.2 Interface Standard] but also include elements of the http://spec.openapis.org/oas/v3.0.3[OpenAPI Specification].  Specifically, this process description languges uses https://json-schema.org/draft/2020-12/json-schema-core.html[JSON Schema] fragments to define the input and output parameters of a process.  As such, this process description provides a bridge from legacy implementations to the OGC API Framework.

The process description allows the following information to be specified:

* An identifier for the process
* Descriptive metadata about the process;
** A title
** A narrative description of the process
** Keywords that can be associated with the process
** References to additional metadata
* A description of each process input specified using a https://json-schema.org/draft/2020-12/json-schema-core.html[JSON Schema] fragment.
* A description of each process output specified using a https://json-schema.org/draft/2020-12/json-schema-core.html[JSON Schema] fragment.
* A job control specification that indicates whether the process can be invoked synchronously, asynchronously, or either.
* An output transmission specification that indicates how the results of a process are retrieved; either by value or by reference
* A section for additional parameters that are intended for communities of use to extend the process description as required

The following clause defines a JSON-encoding of the OGC process description.

=== OGC process description

include::requirements/ogc-process-description/REQ_json-encoding.adoc[]

.link:https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/process.yaml[Schema for a process (process.yaml)]
[source,YAML]
----
include::openapi/schemas/process.yaml[]
----

The schema imports the elements from the <<schema-processSummary, process summary>> and specifies an object for the definition of process inputs and another object for the definition of process outputs.

include::requirements/ogc-process-description/REQ_inputs-def.adoc[]

.link:https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/inputDescription.yaml[Schema for a process input (inputDescription.yaml)]
[source,YAML]
----
include::openapi/schemas/inputDescription.yaml[]
----

include::requirements/ogc-process-description/REQ_input-def.adoc[]

NOTE: The schema fragment specified as the value of the `schema` parameter can be used to validate the corresponding <<input-value-schema,process input value>> in an <<execute-request-body,execute request>>.

include::recommendations/ogc-process-description/REC_input-cardinality.adoc[]

include::requirements/ogc-process-description/REQ_input-binary.adoc[]

include::requirements/ogc-process-description/REQ_input-mixed-type.adoc[]


.Mixed type input example.

The following JSON Schema fragment illustrates how to define an input of mixed type.  In this case, the `imageInput` input can be one a couple of image media types. 

----
   "imageInput": { 
     "schema": {
       "oneOf": [
         {
           "type": "string",
           "contentEncoding": "binary",
           "contentMediaType": "application/tiff; application=geotiff"
         },
         {
           "type": "string",
           "contentEncoding": "binary",
           "contentMediaType": "application/jp2"
         }
       ]
     }
   }
----

.link:https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/outputDescription.yaml[Schema for a process input (outputDescription.yaml)]
[source,YAML]
----
include::openapi/schemas/outputDescription.yaml[]
----

include::requirements/ogc-process-description/REQ_outputs-def.adoc[]

include::requirements/ogc-process-description/REQ_output-def.adoc[]

include::requirements/ogc-process-description/REQ_output-mixed-type.adoc[]

The execution mode for each process is specified using the `jobControlOptions` key in the <<schema-processSummary, process summary>>.  The following requirement indicates how to specify the default execution mode.

include::requirements/ogc-process-description/REQ_default_mode.adoc[]

.Example OGC Process Description.
====
The following URL is an example of retrieving a <<sc_process_description,process description>> from the `/processes/{processId}` endpoint.
[source]
----
https://processing.example.org/processes/EchoProcess
----

The description of the example `EchoProcess` process might be:

[source,json]
----
include::examples/json/ProcessDescription.json[]
----

The `EchoProcess` process simply echoes each process input value it is given.
====
