[[additional-api-building-blocks]]
== Additional API Building Blocks

The core requirements classes of this standard are designed for the following workflow:

. Access the list of available processes
. Access the description of a specific process
. Create an execute JSON request (based on the description) and send it to the server via POST
. Process the status info and/or results

This workflow is useful for generic client that are implemented against the JSON schemas and paths specified in this document. They can communicate with any server implementing the OGC API - Processes. There may be limitations regarding the handling of input and output formats, however. 
 
The approach describe above requires implementors of clients to have knowledge about the standard.

As an alternative that could make it easier for implementors that are not familiar with OGC (API) standards, deviations from strictly following the schemas and paths specified in this standard are permitted.

include::requirements/core/PER_alternative-process-description.adoc[]

This allows server implementations to describe a process, e.g. by defining the request and response body of a POST request to a process endpoint.

include::requirements/core/PER_alternative-process-paths.adoc[]

This allows server implementations to specify alternative paths to processes and jobs. 

An example of an OpenAPI document making use of the building blocks is shown in the following:

TODO: update example
[source,YAML]
----
include::examples/yaml/alternative-api.yaml[]
----

The goals of these additional API building blocks are:

* enabling an more seamless integration of this API with other OGC API standards and
* enabling the use of tools to auto-generate clients from the API description.


