[[sc_security_considerations]]
== Security Considerations

The OGC API - Processes specifies a Web API that enables the execution of computing processes, the retrieval of metadata describing their purpose and functionality and the retrieval of the results of the process execution.

Access control should be considered for the following resources the API specifies:

Requirements class "Core":

* Process description
* Process list
* Job status info
* Job result

Requirements class "Job list"

* Job list 

The following API operations modify resources and therefore require special attention:

Requirements class "Core":

* Execute, HTTP POST 

Requirements class "Dismiss"

* Dismiss, HTTP DELETE

This standard specifies operations that are safe, meaning that they do not modify resources. The execute operation uses HTTP POST to create new processing jobs (executions). This HTTP method is not safe, as it creates new resources, which 


=== Validation

The OGC API - Processes specifies the execute operation using the HTTP POST method, which will be used as example for requests that contain content. The same guidance applies when using different HTTP methods like PUT, which can also contain content. 

==== Validation of incoming Content-types

When sending POST requests, the client will specify the *Content-Type* header of the request content. The server should always check that the *Content-Type* header and the actual request content are of the same type. If there is no *Content-Type* header or the Content-Type is unexpected, the request should be rejected.

==== Input validation

After the Content-Type was checked, the received content of POST requests itself should be validated. Incorrect input validation can lead to injection attacks, memory leakage, and compromised systemsfootnote:[https://www.whitehatsec.com/glossary/content/input-validation].

=== Request rate limitation

To prevent distributed denial of service (DDoS) attacks or other misuse of the API, the number of requests in a given time can be limited. When the limit is exceeded, the HTTP error code 429 (too many requests) should be returned and access tokens could be blocked temporarily.