[[additional-api-building-blocks]]
== Additional API Building Blocks

The core requirements classes of the Processes API standard are designed for the following workflow:

. Access the list of available processes
. Access the description of a specific process
. Create an execute JSON request (based on the description) and send it to the server via POST
. Process the status info and/or results

This workflow is useful for generic client that are implemented against the JSON schemas and paths specified in this standard. Generic clients can communicate with any server implementing the OGC API - Processes. However, there may be limitations regarding the handling of input and output formats. 
 
The approach described above requires implementers of clients to have knowledge about the standard.

An alternative approach that could make implementation easier for those that are not familiar with OGC (API) standards is permitting alternatives to the process description and the paths to processes and jobs. The following permissions do not affect the requirements
 
 * <<req_core_process-op, /req/core/process-op>>,
 * <<req_core_process-success, /req/core/process-success>>, and
 * <<req_core_job, /req/core/job>>.

include::recommendations/core/PER_alternative-process-description.adoc[]

This permission allows server implementations to describe a process, such as by defining the request and response body of a POST request to a process endpoint.

include::recommendations/core/PER_alternative-process-paths.adoc[]

This permission allows server implementations to specify alternative paths to processes and jobs. 

An example of an OpenAPI document making use of the building blocks is shown in the following:

[source,YAML]
----
include::examples/yaml/alternative-api.yaml[]
----

The goals of these additional API building blocks are:

* Enabling an more seamless integration of this API with other OGC API standards and
* Enabling the use of tools to auto-generate clients from the API description.


