[[sc_security_considerations]]
== Security Considerations

The OGC API - Processes specifies a Web API that enables the execution of computing processes, the retrieval of metadata describing their purpose and functionality and the retrieval of the results of the process execution.

Access control should be considered for the following resources the API specifies:

Requirements class "Core":

* Process description
* Process list
* Job status info
* Job result

Requirements class "Job list"

* Job list 

The following API operations modify resources and therefore require special attention:

Requirements class "Core":

* Execute, HTTP POST 

Requirements class "Dismiss"

* Dismiss, HTTP DELETE

=== Information returned by safe operations

This standard specifies operations that are safe, meaning that they do not modify resources. However, the information that is returned by the following operations could be used to exploit the API.

[#table_core_operations_security,reftext='{table-caption} {counter:table-num}']
.Requirements class 'Core' - Overview of core operations and returned sensitive information
[cols="20,30,10,40",options="header"]
!===
|Resource |Path |HTTP method | Information delivered
|Landing page |`/` |GET| General information about the service, links to other endpoints 
|Conformance classes |`/conformance` |GET| List of conformance classes 
|Process list |`/processes` |GET | Process identifiers, links to process descriptions
|Process description |`/processes/{processID}` |GET | Information about a process, e.g. inputs/outputs
|Job status info |`/processes/{processID}/jobs/{jobID}` |GET | Status info, links to results or exceptions
|Job results |`/processes/{processID}/jobs/{jobID}/results` |GET | Job results
!===

The process list contains process identifiers and links to the respective process descriptions.

The process description contains all necessary information needed to execute a process. This information can be used to send an JSON execute request to the API that will pass initial sanity checks, for example checks for the correct input/output identifiers. 

The job status info contains not only status information, but for finished (successful / failed) processes also links to results / exceptions. The results of a process execution will deserve protection as well as the exceptions that could contain hints about why the execution has failed.

[#table_job_list_operation_security,reftext='{table-caption} {counter:table-num}']
.Requirements class 'Job List' - Overview of operations and returned sensitive information
[cols="20,30,10,40",options="header"]
!===
|Resource |Path |HTTP method | Information delivered
|Job list |`/processes/{processID}/jobs` |GET | List of job status information, links to results or exceptions
!===

The retrieval of the job list of a process returns the job ids and links to the respective job status.

=== Unsafe operations

The execute operation uses HTTP POST to create new processing jobs (executions). The HTTP Post method is not safe, as it creates new resources, which poses the following threats:

* Malicious inputs can be provided. Either inline in the execute request JSON or referenced
* The processing can use considerable resources, for example computing time

The dismiss extension uses the HTTP Delete method and can be used to (1) cancel a running job and (2) remove artifacts of a finished job. Both usages pose security related issues. The cancellation of a running job is wasting the resources that the job has used until it was cancelled. The same goes for the removal of results of a (successfully) finished job. The dismiss operation is idempotent, as it must be called on a specific job identifier. Continued dismiss requests result in a HTTP 404 error code. The dismiss operation is not safe, as the state of job resources is altered.