[[sc_terms]]
== Terms, definitions and abbreviated terms

////
// Something equivalent to the following seems to be automatically added by metanorma...
This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards.

In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.
////

[[sc_terms_definitions]]
=== Terms and definitions

[[def_collection]]
==== collection; OGC API collection

(in the context of OGC APIs) A set of spatiotemporal data that may be available through one or more access mechanisms defined by https://www.ogc.org/standards[OGC API standards]. (https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data])

[[def_field-modifiers]]
==== field modifiers

Parameters provided as fields in the relevant execution context, which modifies the obtained data according to applied operations.

[[def_remote-collection]]
==== remote collection

A <<def_collection,collection>> that is available from an external OGC API deployment different from the deployment whose process is being executed.

[[def_remote-process]]
==== remote process

A process that is available from an external OGC API deployment different from the deployment whose process is being executed.

[[sc_terms_abbreviations]]
=== Abbreviated Terms

API:: Application Programming Interface
CWL:: Common Workflow Language
HTTP:: Hypertext Transfer Protocol
JSON:: JavaScript Object Notation
URI:: Uniform Resource Identifier
URL:: Uniform Resource Locator
YAML:: YAML Ain't Markup Language
