[[section_fields_modifiers]]
== Input/Output Fields Modifiers Conformance Classes

=== Requirement Class _Input Fields Modifiers_

The _Input Fields Modifiers_ conformance class specifies how execution requests can modify
an input (including those specified using the _Nested Processes_ and _Remote Processes_ conformance classes,
and extending <<OAProc-1>> conformance classes _Collection Input_, _Remote Collections_)
by filtering its data according to its fields (properties), selecting a subset of the data fields or
deriving new fields from existing ones (e.g., by performing arithmetic),
and/or sorting the data according to the value of fields. An expression language such as the
OGC Common Query Language 2 (CQL2) can be used for this purpose.
https://docs.ogc.org/DRAFTS/21-065.html#_scope[There are plans] to extend CQL2 beyond
boolean predicates to expressions that resolve to other types of values (e.g., numbers or geometry).

NOTE: _Input Fields Modifiers_ has a strong overlap with corresponding requirements of
<<https://docs.ogc.org/DRAFTS/18-062r3.html#rc_collection-input,_Collection Input_>> requirement class from <<OAProc-1>>.
However, this conformance class also extends the capability to other kind of inputs (i.e., not only `"collection"`).
For the case of `"collection"` inputs, where corresponding parametrization fields are defined, they can be considered
equivalent and compatible with this requirement. In some cases (i.e., `"properties"` and `"sortBy"`), this requirement
class provides additional capabilities further extending the _Collection Input_.

include::../requirements/requirements_class_input-fields-modifiers.adoc[]

The following requirements describe the ability of an implementation to modify the
data accessed as an input to a process by first applying a filter (`"filter"`),
selecting a subset of the fields or deriving new fields (`"properties"`) or
sorting the data (`"sortBy"`), before providing the data as input to the process.
In an execution request, these additional keys are specified at the same level as the
`"collection"` defined in the _Collection Input_ conformance class, or the
`"process"` defined in the <<rc_nested-processes,_Nested Process_>> conformance class.

For an input generated by a nested process, this capability is equivalent to the
<<rc_output-fields-modifiers,_Output Fields Modifiers_>> conformance class from the perspective of that nested process.
For a remote process (as defined in <<rc_remote-core-processes,_Remote Core Processes_>> conformance class)
that supports <<rc_output-fields-modifiers,_Output Fields Modifiers_>> , or
for a collection (or a process supporting _Collection Output_) with a data access mechanism providing the required functionality,
it is preferable to let the remote process or collection access handle the modification to lower bandwidth and processing requirements.

For an input from a <<def_remote-collection,_remote collection_>>, a data access mechanism for the collection may readily support some or all of these parameters (e.g., _OGC API - Features - Part 3: Filtering_).
In this case, it is preferable for the Implementation to query the data with the relevant parameters.

This ability to pass on these modifiers to remote data and processing sources allows to easily bring a certain category of algorithms close to the data through simple standard expressions.

The extent to which an implementation support these field modifiers capabilities depends on its stated level of conformance to one or more expression language.

==== Filtering

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_filtering.adoc[]

==== Selecting and Deriving Fields

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_derived-fields.adoc[]

==== Sorting

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_sorting.adoc[]

=== Requirement Class _Output Fields Modifiers_

The _Output Fields Modifiers_ conformance class specifies how execution requests can modify
the data output from a process by filtering its data according to its fields (properties), selecting a subset of the data fields or
deriving new fields from existing ones (e.g., by performing arithmetic),
and/or sorting the data according to the value of fields. An expression language such as the
OGC Common Query Language 2 (CQL2) can be used for this purpose.
https://docs.ogc.org/DRAFTS/21-065.html#_scope[There are plans] to extend CQL2 beyond
boolean predicates to expressions that resolve to other types of values (e.g., numbers or geometry).

This capability is available whether using the
<<https://docs.ogc.org/DRAFTS/18-062r3.html#rc_collection-output,_Collection Output_>> requirement class from <<OAProc-1>>,
or the synchronous or asynchronous execution capabilities of <<OAProc-1>>.

NOTE: Contrary to <<rc_input-fields-modifiers,_Input Fields Modifiers_>> where <<def_field-modifiers>> are partially covered by
<<OAProc-1>> and this standard (_Part 3:_), the _Output Fields Modifiers_ are entirely defined by this standard.
However, they are still complementary to the <<https://docs.ogc.org/DRAFTS/18-062r3.html#rc_collection-output,_Collection Output_>>
if a `response=collection` is requested, and can also be employed by themselves onto the single output produced by a process execution.

include::../requirements/requirements_class_output-fields-modifiers.adoc[]

The following requirements describe the ability of an implementation to modify the
data output from a process by applying a filter (`"filter"`),
selecting a subset of the fields or deriving new fields (`"properties"`) or
sorting the data (`"sortBy"`), before returning the data as an output of a process.
In an execution request, these additional keys are specified at the same level as the
`"process"` defined in the <<rc_nested-processes,_Nested Process_>> conformance class, or at the top-level of an execution request
as defined in <<OAProc-1>>.

When a nested process is used as an input to another process, this capability is equivalent to the
_Input Fields Modifiers_ conformance class from the perspective of the parent process receiving the output of the nested process.
For a <<rc_remote-core-processes,_Remote Process_>> that supports _Output Fields Modifiers_, or
supports _Collection Output_ from <<OAProc-1>> with a data access mechanism providing the required functionality,
it is preferable to let the remote process handle the modification to lower bandwidth and processing requirements.

The extent to which an implementation support these capabilities depends on its
stated level of conformance to one or more expression language.

==== Filtering

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_filtering.adoc[]

==== Selecting and Deriving Fields

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_derived-fields.adoc[]

==== Sorting

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_sorting.adoc[]
