
[abstract]
== Abstract

OGC API standards define modular API building blocks to spatially enable Web APIs in a consistent way. The <<OpenAPI,OpenAPI specification>> is used to define the API building blocks.

OGC API Processes provides API building blocks to describe, execute, monitor
and retrieve results of Web-accessible processes.  OGC API Processes is
comprised of multiple parts, each of them is a separate standard.

This part extends the core capabilities specified in <<OAProc-1>> with the ability to chain nested processes,
refer to external processes and collections accessible via OGC API standards, and trigger execution of processes through OGC API data delivery specifications
such as OGC API - Features, Tiles, Maps and Coverages.

The development of this extension has been financially supported by GeoConnections, a national collaborative initiative led by Natural Resources Canada.
GeoConnections supports the integration and use of the Canadian Geospatial Data Infrastructure (CGDI), an on-line resource that improves the sharing,
access and use of open geospatial information.

CAUTION: This is a DRAFT version of the 3rd part of the OGC API - Processes standards.
This draft is not complete and there are open issues that are still under discussion.


.Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[.preface]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[cols="2",options="header,unnumbered"]
|===
| Name | Affiliation
| Jerome Jacovella St-Louis _(editor)_ | Ecere Corporation
|===
