[[ats_dismiss_job-dismiss-success]]
[abstract_test]
====
[%metadata]
label:: /conf/dismiss/job-dismiss-success
subject:: <<req_dismiss_job-dismiss-success,/req/dismiss/job-dismiss-success>>
test-purpose:: Validate that the content returned when dismissing a job complies with the required structure and contents.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====

[.component,class=step]
--
Validate that a document was returned with an HTTP status code of 200.
--

[.component,class=step]
--
Validate that the status is the response is set to "dismissed".
--

[.component,class=step]
--
Validate the process list content for all supported media types using the resources and tests identified in <<job-dismiss-schema>>
--
=====

The response to dismissing a job can be presented in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the against that schema. All supported formats should be exercised.
====

[[job-dismiss-schema]]
.Schema and Tests for Dismissing a Job
[cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml[statusInfo.yaml] |<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml[statusInfo.yaml] |<<ats_json_content,/conf/json/content>>
|===
