[[ats_job-list_duration-response]]

[abstract_test]
====
[%metadata]
identifier:: /conf/job-list/duration-response
target:: /req/job-list/duration-response
test-purpose:: Validate that the `minDuration` and `maxDuration` query parameter are processed correctly.
test-method::
+
--
1. Get a list of jobs as per test <<ats_job-list_job-list-op,/conf/job-list/job-list-op>> and append the `minDuration` query parameter to the request.

2. Compute the duration of each job listed in the response document as per requirements <<req_job-list_duration-response,/req/job-list/status-response, E or F>> depending on the current status of the job.

3. Verify that the computed duration of each job listed in the response is at least as long as the specified value of the `minDuration` query parameter.

4. Get a list of jobs as per test <<ats_job-list_job-list-op,/conf/job-list/job-list-op>> and append the `maxDuration` query parameter to the request.

5. Compute the duration of each job listed in the response document as per requirements <<req_job-list_duration-response,/req/job-list/status-response, E or F>> depending on the current status of the job.

6. Verify that the computed duration of each job listed in the response is no longer than the specified value of the `maxDuration` query parameter.

7. Get a list of jobs as per test <<ats_job-list_job-list-op,/conf/job-list/job-list-op>> and append the `minDuration` and `maxDuration` query parameters to the request.

8. Compute the duration of each job listed in the response document as per requirements <<req_job-list_duration-response,/req/job-list/status-response, E or F>> depending on the current status of the job.

9. Verify that the computed duration of each job listed in the response is at least as long as the specified value of the `minDuration` query parameter AND no longer than the value of the  `maxDuration` query parameter.
--
====
