.Preface

This Standard specified how to "wrap" computational tasks into an executable process that can be invoked by a client application. Examples of computational processes that can be supported by implementations of API Processes include raster algebra, geometry buffering, constructive area geometry, routing, imagery analysis, AI models, and others.  Specifically, the OGC API - Processes Standard defines how a client application can request the execution of a process, how the inputs to that process can be provided, and how the outputs from that process are retrieved. 

[abstract]
== Abstract

The OGC API - Processes Standard is a resource-oriented API that allows for the execution of computing processes and the retrieval of metadata describing those processes. It is the modern, RESTful successor to the older Web Processing Service (WPS) standard.  It utilizes OpenAPI, JSON and modern web architectural patterns to make geospatial processing more accessible to web developers.

The key benefits of the Standard are:

* **Developer friendly:** By default, the Standard uses JSON and integrates easily with modern web frameworks and tools like Swagger/ReDoc.

* **Scalable:** The Standard is designed to work well with cloud-native architectures, microservices and containerized environments.

* **Modular:** The "building-blocks" approach allows servers to implement only what they need (e.g. a server might support process execution but not dynamic process deployment).

* **Interoperable:** Standardizing how parameters are passed to algorithms ensures that a client can trigger a process on any compliant server regardless of the underlying programming language (e.g. C, Python, Java, etc.)

Like other OGC APIs (such as Features or Records), OGC API Processes uses a common core for landing pages, conformance declarations, and API definitions. This consistency allows developers to use similar patterns across different types of geospatial web services.

== Acknowledgements

Requirements integrated within version 2.0 of this OGC API - Processes Standard was sourced from Part 3: Workflows, whose development was undertaken as part of GeoConnections 2020-2021 and 2025-2027 projects GNS20-21IFP02 (Modular OGC API Workflows) and GNS25-27IFP2 (Advancing and Implementing OGC Standards for GeoDataCubes, DGGSs, Data Stores for Digital Twins and Cartographic Symbology). Financial support provided by GeoConnections, a national collaborative initiative led by Natural Resources Canada. GeoConnections supports the modernization of the Canadian Geospatial Data Infrastructure (CGDI). The CGDI is the collection of geospatial data, standards, policies, applications, and governance that facilitate its access, use, integration, and preservation.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

.Table of submitters
[%unnumbered]
|===
| *Name* | *Affiliation*
|Benjamin Pross _(editor)_ | 52°North GmbH
|Stan Tillman|Hexagon
|Panagiotis (Peter) A. Vretanos _(editor)_ |CubeWerx Inc.
|Jérôme Jacovella-St-Louis|Ecere Corporation
|Pedro Gonçalves|Terradue Srl
|Gérald Fenoy| Gérald Fenoy (Individual Member)
|Francis Charette-Migneault| Centre de Recherche Informatique de Montréal (CRIM)
|Cristiano Lopes|European Space Agency (ESA)
|Christophe Noel | Spacebel
|===
