
== Terms, definitions and abbreviated terms

=== Terms and definitions

[[def-collection]]
==== collection; OGC API collection

A resource that may be available as one or more sub-resource distributions that conform to one or more https://www.ogc.org/standards[OGC API standards]. (https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data])

[[def-collection-description]]
==== collection description document

A resource accessible at the OGC API path `/collections/{collectionId}` that provides metadata about a <<def-collection,collection>>.

==== dataset

A collection of data, published or curated by a single agent, and available for access or download in one or more representations. (https://www.w3.org/TR/vocab-dcat-2/[Data Catalog Vocabulary (DCAT) - Version 2])

==== distribution

A specific representation of a dataset. A dataset might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above). (https://www.w3.org/TR/vocab-dcat-2/[Data Catalog Vocabulary (DCAT) - Version 2])

EXAMPLE: a downloadable file, an RSS feed or an API.

==== job

The (processing) job is a server-side object created by a processing service for a particular process execution. A job may be latent in the case of synchronous execution or explicit in the case of asynchronous execution. Since the client has only oblique access to a processing job, a Job ID is used to monitor and control a job.

==== JSON

JavaScript Object Notation is a lightweight data-interchange format. JSON is easy for humans to read and write and it is easy for machines to parse and generate.

==== link

The term "link" is commonly used as substitute for URL or URI. In this Standard, "link" refers to an element described by the schema for a link as shown at <<link-schema,link.yaml>>. This is a JSON element containing properties such as "rel" (relation) and "href". The value of the "href" property is an URI.

==== link header

HTTP Link header, as defined in <<rfc8288,RFC 8288 (Web Linking)>>.

[[def-local-collection]]
==== local collection

A <<def-collection,collection>> that is local to the <<def-deployment,OGC API deployment>> <<def-data-access-mechanism,currently being accessed>>.

[[def-data-access-mechanism]]
==== OGC API data access mechanism

A method or procedure, that conforms to an https://www.ogc.org/standards/[OGC API Standard], used to control how users or systems can access and interact with data.

EXAMPLE: https://docs.ogc.org/is/20-057/20-057.html[_OGC API - Tiles - Part 1: Core_], https://docs.ogc.org/DRAFTS/19-087.html[_OGC API - Coverages - Part 1: Core_], https://docs.ogc.org/DRAFTS/21-038r1.html[_OGC API - Discrete Global Grid Systems - Part 1: Core_], https://docs.ogc.org/is/17-069r4/17-069r4.html[_OGC API - Features - Part 1: Core_], https://docs.ogc.org/is/19-086r6/19-086r6.html[_OGC API - Environmental Data Retrieval Standard_], https://docs.ogc.org/is/20-058/20-058.html[_OGC API - Maps - Part 1: Core_]

[[def-deployment]]
==== OGC API deployment

An implementation of an https://www.ogc.org/standards/[OGC API Standard] that is accessible to users and other system typically through the internet.

==== process

A process p is a function that for each input returns a corresponding output

[stem%unnumbered]
++++
p: X -> Y
++++

where stem:[X] denotes the domain of arguments stem:[x] and stem:[Y] denotes the co-domain of values y. In this Standard, process arguments are referred to as process inputs and result values are referred to as process outputs. Processes that have no process inputs represent value generators that deliver constant or random process outputs.

The term "process" is one of the most used terms both in the information and geosciences domain. If not stated otherwise, this Standard uses the term process as an umbrella term for any algorithm, calculation or model that either generates new data or transforms some input data into output data as defined in section 4.1 of the OGC WPS 2.0 standard.

==== process description

A process description is an information model that specifies the interface of a process. A process description is used for a machine-readable description of the process itself but also provides some basic information about the process inputs and outputs.


==== process execution

The execution of a process is an action that calculates the outputs of a given process for a given set of data inputs.


==== process input

Process inputs are the arguments of a process and refer to data provided to a process. Each process input is an identifiable item.


==== process offering

A process offering is an identifiable process that may be executed on a particular service instance. A process offering contains a process description as well as service-specific information about the supported execution protocols (e.g. synchronous and asynchronous execution).

==== process output

Process outputs are the results of a process and refer to data returned by a process. Each process output is an identifiable item.

[[explicit-process-output]]
==== process output (explicitly requested)

A process output with identifier `{outputID}` that is explicitly specified in the "outputs" section of an <<execute-request-body,execute request>>.

[[implicit-process-output]]
==== process output (implicitly requested)

A process output that is defined in the <<sc_process_description,description of a process>> and is generated as a result of an <<execute-request-body,execute request>> where the "outputs" parameter has been omitted.  Omitting the "outputs" parameters of an <<execute-request-body,execute request>> is equivalent to explicitly requesting all of the outputs defined in the <<sc_process_description,process description>>

[[def-remote-collection]]
==== remote collection

A <<def-collection,collection>> that is not local to the <<def-deployment,OGC API deployment>> <<def-data-access-mechanism,currently being accessed>>.

==== REST

The Representational State Transfer (REST) style is an abstraction of the architectural elements within a distributed hypermedia system. REST focuses on the roles of components, the constraints upon their interaction with other components, and their interpretation of significant data elements. It encompasses the fundamental constraints upon components, connectors, and data that define the basis of the Web architecture, and thus the essence of its behavior as a network-based application. An API that conforms to the REST architectural principles/constraints is called a *RESTful API*. (Source: https://docs.ogc.org/is/18-088/18-088.html#_rest[OGC 18-088])

[[value-source-server]]
==== Value source server

A server that implements one or more <<def-data-access-mechanism,data access mechanisms>> for accessing data from an <<def-collection,OGC API collection>>.  The server acts as a source of values that are passed to a process being executed by an implementation of this Standard.

=== Abbreviated Terms

API:: Application Programming Interface
CITE:: Compliance Interoperability & Testing Evaluation
CRS:: Coordinate Reference System
GML:: Geography Markup Language
HTTP:: Hypertext Transfer Protocol
ISO:: International Organization for Standardization
JSON:: JavaScript Object Notation
KVP:: Key-Value Pair
MIME:: Multipurpose Internet Mail Extensions
OGC:: Open Geospatial Consortium
REST:: Representational State Transfer
URI:: Uniform Resource Identifier
URL:: Uniform Resource Locator
WPS:: Web Processing Service
XML:: Extensible Markup Language
