
[[Callbacks]]
== Requirements Class "Callback"

The Callback conformance class specifies a callback mechanism for completed jobs. In contrast to the pull-based mechanism specified in <<sc_create_job>> and <<sc_retrieve_status_info>>, this conformance class specifies a push-based mechanism, where a subscriber-URL is passed to the API in the execute request. After the job is completed, the result response is sent to the specified URL.

include::../requirements/requirements_class_callback.adoc[]

include::../requirements/callback/REQ_job-creation-callback.adoc[]

.A callback in the execute operation
====
[source,yaml]
----
include::../examples/yaml/callbacks.yaml[]
----
====

If the server implements this conformance class, the optional subscriber element of the execute request JSON SHALL be used.

Adding multiple callbacks is possible for getting progress updates and notifications of the success or failure of a job completion.

Further guidance about how to use callbacks can be found in the https://swagger.io/docs/specification/callbacks/[OpenAPI documentation].
