
[[mediatypes]]
== Media Types

JSON media types that would typically be used in a server that supports JSON are:

* `application/json` for all resources.

The typical HTML media type for all "web pages" in a server would be:

* `text/html`.

The media type for an OpenAPI 3.0 definition is
`application/vnd.oai.openapi+json;version=3.0` (JSON) or
`application/vnd.oai.openapi;version=3.0` (YAML).

NOTE: The OpenAPI media types have not yet been registered with IANA and may
change in the future.


As previously mentioned in the <<con-neg-by-profile,"Content negotiations by profile">> clause, in some circumstances the use of generic media types, such as `application/json`, is too ambiguous.  In order to more specifically identify responses generated by a server compliant with this Standard, the following profile URIs are defined:

[[profile-uris]]
.Profile identifiers
[cols="2,6"]
|===
^|*Profile URI* ^|*Description*
|https://www.opengis.net/dev/profile/OGC/0/ogc-process-list |A JSON-encoded document that contains a <<sc_process_list_response,list of processes>> offered by a server.

|https://www.opengis.net/dev/profile/OGC/0/ogc-process-description |A JSON-encoded OGC process description as defined in <<process_description_schema,Requirements Class "OGC Process Description">>.

|https://www.opengis.net/dev/profile/OGC/0/ogc-execute-request |A JSON-encoded document that contains an <<execute-request-body,execute request>>.

|https://www.opengis.net/dev/profile/OGC/0/jobs-list |A JSON-encoded document that contains a <<sc_job_list_response,list of jobs>>.

|https://www.opengis.net/dev/profile/OGC/0/job-description |A JSON-encoded document that contains <<sc_status_info_response,status information about a job>>.

|https://www.opengis.net/dev/profile/OGC/0/ogc-results |A JSON document that contains <<sc_execute_response,processing results>> (<<schema_results,results.yaml>>).

|===
