[[sc_terms]]
== Terms, definitions and abbreviated terms

[[sc_terms_definitions]]
=== Terms and definitions

[[def_collection]]
==== collection; OGC API collection

(in the context of OGC APIs) A set of spatiotemporal data that may be available through one or more access mechanisms defined by https://www.ogc.org/standards[OGC API standards]. (https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data])

[[def_collection-description]]
==== collection description document

A resource accessible at the OGC API path `/collections/{collectionId}` that provides metadata about a <<def_collection,collection>>.

[[def_dataset]]
==== dataset

A collection of data, published or curated by a single agent, and available for access or download in one or more representations. (https://www.w3.org/TR/vocab-dcat-2/[Data Catalog Vocabulary (DCAT) - Version 2])

[[def_distribution]]
==== distribution

A specific representation of a dataset. A dataset might be available in multiple distributions that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above). (https://www.w3.org/TR/vocab-dcat-2/[Data Catalog Vocabulary (DCAT) - Version 2])

EXAMPLE: a downloadable file, an RSS feed or an API.

[[def_job]]
==== job

The (processing) job is a server-side object created by a processing service for a particular process execution. A job may be latent in the case of synchronous execution or explicit in the case of asynchronous execution. Since the client has only oblique access to a processing job, a Job ID is used to monitor and control a job.

[[def_JSON]]
==== JSON

JavaScript Object Notation is a lightweight text-based, data-interchange format.

[[def_link]]
==== link

The term "link" is commonly used as substitute for URL or URI. In this Standard, "link" refers to an element described by the schema for a link as shown at <<link-schema,link.yaml>>. This is a JSON element containing properties such as "rel" (relation) and "href". The value of the "href" property is an URI.

[[def_link-header]]
==== link header

HTTP Link header, as defined in <<rfc8288,RFC 8288 (Web Linking)>>.

[[def_local-collection]]
==== local collection

A <<def_collection,collection>> that is local to the <<def_deployment,OGC API deployment>> <<def_data-access-mechanism,currently being accessed>>.

[[def_data-access-mechanism]]
==== OGC API data access mechanism

(in the context of OGC APIs) A mechanism defined by an OGC API Standard to access spatiotemporal data from a <<def_collection,collection>>/

EXAMPLE: https://docs.ogc.org/is/20-057/20-057.html[_OGC API - Tiles - Part 1: Core_], https://docs.ogc.org/DRAFTS/19-087.html[_OGC API - Coverages - Part 1: Core_], https://docs.ogc.org/DRAFTS/21-038r1.html[_OGC API - Discrete Global Grid Systems - Part 1: Core_], https://docs.ogc.org/is/17-069r4/17-069r4.html[_OGC API - Features - Part 1: Core_], https://docs.ogc.org/is/19-086r6/19-086r6.html[_OGC API - Environmental Data Retrieval Standard_], https://docs.ogc.org/is/20-058/20-058.html[_OGC API - Maps - Part 1: Core_]

[[def_deployment]]
==== OGC API deployment

An implementation of an https://www.ogc.org/standards/[OGC API Standard] that is accessible to users and other system(s) typically through the Web.

[[def_process]]
==== process

A process _p_ is a function that for each input returns a corresponding output

[stem%unnumbered]
++++
p: X -> Y
++++

where stem:[X] denotes the domain of arguments stem:[x] and stem:[Y] denotes the co-domain of values y. In this Standard, process arguments are referred to as process inputs and result values are referred to as process outputs. Processes that have no process inputs represent value generators that deliver constant or random process outputs.

The term "process" is one of the most used terms both in the information and geosciences domain. If not stated otherwise, this Standard uses the term process as an umbrella term for any algorithm, calculation or model that either generates new data or transforms some input data into output data as defined in section 4.1 of the OGC WPS 2.0 standard.

[[def_process-description]]
==== process description

A specific documented account of steps, roles, and rules involved in a computing <<def_process,process>>, often described using standard like the https://swagger.io/specification/[OpenAPI Standard].

[[def_process_exection]]
==== process execution

The execution of a <<def_process,process>> is an action that calculates the outputs of a given process for a given set of data inputs.

[[def_process-input]]
==== process input

Process inputs are the arguments of a process and refer to data provided to a <<def_process,process>>. Each process input is an identifiable item.

[[def_process-offering]]
==== process offering

A process offering is an identifiable <<def_process,process>> that may be executed on a particular service instance. A process offering contains a process description as well as service-specific information about the supported execution protocols (e.g. synchronous and asynchronous execution).

[[def_process-output]]
==== process output

Process outputs are the selectable outputs of a <<def_process,process>> and refer to data results returned by the execution of that process. Each process output is an identifiable item.

[[def_explicit-process-output]]
==== process output (explicitly requested)

A process output that is defined in the <<sc_process_description,description of a process>> and is explicitly specified using its identifier `{outputID}` in the "outputs" section of an <<execute-request-body,execute request>>.

[[def_implicit-process-output]]
==== process output (implicitly requested)

A process output that is defined in the <<sc_process_description,description of a process>> and is generated as a result of an <<execute-request-body,execute request>> where the "outputs" parameter has been omitted.  Omitting the "outputs" parameters of an <<execute-request-body,execute request>> is equivalent to explicitly requesting all of the outputs defined in the <<sc_process_description,process description>>

[[def_remote-collections]]
==== remote collections

A <<def_collection,collection>> that is available from an external OGC API deployment different from the deployment whose process is being executed.

[[def_REST]]
==== REST

The Representational State Transfer (REST) style is an abstraction of the architectural elements within a distributed hypermedia system. REST focuses on the roles of components, the constraints upon their interaction with other components, and their interpretation of significant data elements. It encompasses the fundamental constraints upon components, connectors, and data that define the basis of the Web architecture, and thus the essence of its behavior as a network-based application. An API that conforms to the REST architectural principles/constraints is called a *RESTful API*. (Source: https://docs.ogc.org/is/18-088/18-088.html#_rest[OGC 18-088])

[[def_value-source-server]]
==== Value source server

A server that implements one or more <<def_data-access-mechanism,data access mechanisms>> for accessing data from an <<def_collection,OGC collection>>.  The server acts as a source of values that are passed to a process being executed by an implementation of this Standard.

[[sc_terms_abbreviations]]
=== Abbreviated Terms

API:: Application Programming Interface
CITE:: Compliance Interoperability & Testing Evaluation
CRS:: Coordinate Reference System
GML:: Geography Markup Language
HTTP:: Hypertext Transfer Protocol
ISO:: International Organization for Standardization
JSON:: JavaScript Object Notation
KVP:: Key-Value Pair
MIME:: Multipurpose Internet Mail Extensions
OGC:: Open Geospatial Consortium
REST:: Representational State Transfer
URI:: Uniform Resource Identifier
URL:: Uniform Resource Locator
WPS:: Web Processing Service
XML:: Extensible Markup Language
