== Collections

[[section_collection_input]]
=== REQUIREMENTS CLASS "COLLECTION INPUT"

==== Overview

The _Collection Input_ conformance class allows an <<def-collection,OGC API collection>>, available using one or more <<def-data-access-mechanisms,OGC API data access mechanisms>>, to be specified as an input to a process.

Unless an implementation also conforms to the <<remote_collections,_Remote Collections_>> conformance class, only <<def-collection,collections>> that are locally accessible in the current <<def-deployment,OGC API deployment>> are supported.

include::../requirements/requirements_class_collection-input.adoc[]

The following requirements describe how an <<execute-request-body,execute requests>> references an <<def-collection,OGC API collection>> and how an implementation requests data from that collection to use as input to a process.

==== Referencing a collection

include::../requirements/collection-input/REQ_collection-input_referenced-collection.adoc[]

==== Accessing data from a collection

include::../requirements/collection-input/REQ_collection-input_collection-access.adoc[]



[[remote_collections]]
=== REQUIREMENTS CLASS "REMOTE COLLECTIONS"

==== Overview

The _Remote Collections_ conformance class allows to reference a remote OGC API collection
in addition to any local collections.

If the _Nested Processes_ conformance class is also supported, but _Remote Processes_ is not,
an implementation still provides the ability to substitute a collection by remote nested processes
supporting the _Collection Output_ conformance class as input to a process.

include::../requirements/requirements_class_remote-collections.adoc[]

The following requirements describe how an <<execute-request-body,execute requests>> references a remote OGC API collection
and how an implementation requests data from that collection to use as an input to a process.

==== Referencing a remote collection

include::../requirements/remote-collections/REQ_remote-collections_referenced-collection.adoc[]

==== Accessing data from a remote collection

include::../requirements/remote-collections/REQ_remote-collections_collection-access.adoc[]



[[section_collection_output]]
=== REQUIREMENTS CLASS "COLLECTION OUTPUT"

==== Overview 

The _Collection Output_ conformance class specifies how clients can trigger the
execution of a process or workflow for a specific area, time and resolution of interest
as a result of requesting output data using OGC API data access mechanisms, such as
_OGC API - Tiles_, _DGGS_, _Coverages_, _Features_, _EDR_, or _Maps_.

This provides an alternative to the synchronous and asynchronous execution mechanisms
defined in _OGC API - Processes - Part 1: Core_ for which area, time and resolution of interest
are hardcoded in the <<execute-request-body,execute request>>. With _Core_, when lengthy batch processing is not desirable,
completely new <<execute-request-body,execute requests>> returning a partial output must continuously be re-submitted.

This conformance class allows to submit an <<execute-request-body,execute request>> once and then access the output
using mechanisms widely supported by clients in a manner completely agnostic of process execution.

Compared to separate <<execute-request-body,execute requests>>, this mechanism makes it easier for implementations to optimize
for scenarios where clients will stream small partial outputs from the same pre-established processing
pipeline. Parsing the <<execute-request-body,execute request>>, validating inputs, and handshakes with remote components of a workflow
only need to be performed once. An implementation could also preempt future requests based on past requests,
offsetting the latency of a complex distributed workflow.

A collection document for the result generated from a workflow MAY provide a link to the source definition of that
workflow (link relation type: `http://www.opengis.net/def/rel/ogc/1.0/workflow`).

A service MAY also implement the capability to deploy a workflow as a persistent collection e.g., by supporting a `POST`
method for the `/collections` end-point accepting a JSON workflow definition (<<execute-request-body,execute request>>) as payload.

include::../requirements/requirements_class_collection-output.adoc[]

The following requirements describe an execution mechanism where a client is redirected (using a `303` _See Other_ HTTP
status code and a `Location:` header)
to an OGC API landing page or collection description document,
which provides links to request output data using standard OGC API data access mechanisms, triggering on-demand processing
for a particular area, time and resolution of interest.

==== `response` query parameter

include::../requirements/collection-output/REQ_collection-output_response-query-parameter.adoc[]

==== Collection Response

A request for a collection response is only valid for an <<execute-request-body,execute request>> generating or selecting a single output
which can be retrieved using an OGC API data access mechanism.

include::../requirements/collection-output/REQ_collection-output_collection-response.adoc[]

==== Landing Page Response

A request for a landing page response is valid for an <<execute-request-body,execute request>> generating one or more outputs
which can be retrieved using an OGC API data access mechanism.

include::../requirements/collection-output/REQ_collection-output_landing-page-response.adoc[]

==== Collection Output expiry

include::../recommendations/collection-output/PER_collection-output_expiry.adoc[]

==== Data Access Mechanisms

include::../requirements/collection-output/REQ_collection-output_data-access-mechanisms.adoc[]


[[section_fields_modifiers]]
=== REQUIREMENTS CLASS "INPUT FIELDS MODIFIERS"

==== Overview

The _Input Fields Modifiers_ conformance class specifies how <<execute-request-body,execute requests>> can modify
an input (including those specified using the _Collection Input_, _Remote Collections_, _Nested Processes_ and _Remote Processes_ conformance classes)
by filtering its data according to its fields (properties), selecting a subset of the data fields or
deriving new fields from existing ones (e.g., by performing arithmetic),
and/or sorting the data according to the value of fields. An expression language such as the
OGC Common Query Language 2 (CQL2) can be used for this purpose.
http://docs.ogc.org/DRAFTS/21-065.html#_scope[There are plans] to extend CQL2 beyond
boolean predicates to expressions that resolve to other types of values (e.g., numbers or geometry).

include::../requirements/requirements_class_input-fields-modifiers.adoc[]

The following requirements describe the ability of an implementation to modify the
data accessed as an input to a process by first applying a filter (`"filter"`),
selecting a subset of the fields or deriving new fields (`"properties"`) or
sorting the data (`"sortBy"`), before providing the data as input to the process.
In an <<execute-request-body,execute request>>, these additional keys are specified at the same level as the
`"collection"` defined in the _Collection Input_ conformance class, or the
`"process"` defined in the _Nested Process_ conformance class.

For an input generated by a nested process, this capability is equivalent to the
_Output Fields Modifiers_ conformance class from the perspective of that nested process.
For a remote process (as defined in _Remote Processes_ conformance class) that supports _Output Fields Modifiers_, or
for a collection (or a process supporting _Collection Output_) with a data access mechanism providing the required functionality,
it is preferable to let the remote process or collection access handle the modification to lower bandwidth and processing requirements.

For an input from a _remote collection_, a data access mechanism for the collection may readily support some or all of these parameters (e.g., _OGC API - Features - Part 3: Filtering_).
In this case, it is preferable for the Implementation to query the data with the relevant parameters.

This ability to pass on these modifiers to remote data and processing sources allows to easily bring a certain category of algorithms close to the data through simple standard expressions.

The extent to which an implementation support these field modifiers capabilities depends on its stated level of conformance to one or more expression language.

==== Filtering

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_filtering.adoc[]

==== Selecting and Deriving Fields

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_derived-fields.adoc[]

==== Sorting

include::../requirements/input-fields-modifiers/REQ_input-fields-modifiers_sorting.adoc[]

=== REQUIREMENTS CLASS "OUTPUT FIELDS MODIFIERS"

==== Overview

The _Output Fields Modifiers_ conformance class specifies how <<execute-request-body,execute requests>> can modify
the data output from a process by filtering its data according to its fields (properties), selecting a subset of the data fields or
deriving new fields from existing ones (e.g., by performing arithmetic),
and/or sorting the data according to the value of fields. An expression language such as the
OGC Common Query Language 2 (CQL2) can be used for this purpose.
http://docs.ogc.org/DRAFTS/21-065.html#_scope[There are plans] to extend CQL2 beyond
boolean predicates to expressions that resolve to other types of values (e.g., numbers or geometry).

This capability is available whether using the _Collection Output_ conformance class,
or the synchronous or asynchronous execution capabilities of _OGC API - Processes - Part 1: Core_.

include::../requirements/requirements_class_output-fields-modifiers.adoc[]

The following requirements describe the ability of an implementation to modify the
data output from a process by applying a filter (`"filter"`),
selecting a subset of the fields or deriving new fields (`"properties"`) or
sorting the data (`"sortBy"`), before returning the data as an output of a process.
In an <<execute-request-body,execute request>>, these additional keys are specified at the same level as the
`"process"` defined in the _Nested Process_ conformance class, or at the top-level of an <<execute-request-body,execute request>> 
as defined in _OGC API - Processes - Part 1: Core_.

When a nested process is used as an input to another process, this capability is equivalent to the
_Input Fields Modifiers_ conformance class from the perspective of the parent process receiving the output of the nested process.
For a remote process (as defined in _Remote Processes_ conformance class) that supports _Output Fields Modifiers_, or
supports _Collection Output_ with a data access mechanism providing the required functionality,
it is preferable to let the remote process handle the modification to lower bandwidth and processing requirements.

The extent to which an implementation support these capabilities depends on its
stated level of conformance to one or more expression language.

==== Filtering

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_filtering.adoc[]

==== Selecting and Deriving Fields

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_derived-fields.adoc[]

==== Sorting

include::../requirements/output-fields-modifiers/REQ_output-fields-modifiers_sorting.adoc[]
