[[requirements-class-openapi_3_0-clause]]
== Requirements Class "OpenAPI 3.0"

=== Basic requirements

APIs conforming to this requirements class are documented as an link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oasDocument[OpenAPI Document].

include::../requirements/requirements_class_oas30.adoc[]

include::../requirements/oas30/REQ_oas-definition-1.adoc[]

include::../requirements/oas30/REQ_oas-definition-2.adoc[]

include::../requirements/oas30/REQ_oas-impl.adoc[]

=== Complete definition

include::../requirements/oas30/REQ_completeness.adoc[]

NOTE: Implementations of the Processes API may also include capabilities that are not specified in this Standard such as access-control (see <<security,Security>>), support for web cache validation, handling of CORS or the use of HTTP redirection.  These additional capabilities make use of HTTP status codes that are beyond the regular set of code such as `200` for successful GET requests and `400`, `404` or `500` for error situations (see <<http_status_codes>>).  These additional codes would not necessarily be specified in a OpenAPI document and so clients must be prepared to receive responses not documents in the OpenAPI definition.  For example, additional error codes may be generated in the transport layer which is outside the server. 

[[exceptions]]
=== Exceptions

include::../requirements/oas30/REQ_exception-codes.adoc[]

.An exception response object definition
====
[source,yaml]
----
description: An error occurred.
content:
  application/json:
    schema:
      $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/openapi/schemas/common-core/exception.yaml
  text/html:
    schema:
      type: string
----
====

[[security]]
=== Security

include::../requirements/oas30/REQ_security.adoc[]

The OpenAPI specification currently supports the following link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object[security schemes]:

* HTTP authentication,
* an API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.
