[[clause_collections]]
== Collections

[[sc_collection-input]]
=== REQUIREMENTS CLASS "COLLECTION INPUT"

[[sc_collection-input_overview]]
==== Overview

The _Collection Input_ Requirements Class supports specifying as an input to a process an <<def_collection,OGC API accessible collection>> via using one or more <<def_data-access-mechanism,OGC API data access mechanisms>>.  Specifically, the processing server acts as a client and fetches values from the <<def_collection,OGC API accessible collection>> using one of the available <<def_data-access-mechanism,OGC API data access mechanisms>> and then feeds the fetched values as input values to the process being executed.  The server from which input values are retrieved is referred to as the <<def_value-source-server,_value source server_>>.

Unless an implementation also conforms to the <<sc_remote-collections,_Remote Collections_>> conformance class, only <<def_collection,collections>> that are locally accessible in the current <<def_deployment,OGC API deployment>> are supported.

Unless an implementation also conforms to the <<sc_local-filtering,_Local Filtering_>> conformance class, filtering of values retrieved from an <<def_collection,OGC API accessible collection>> is performed by the <<def_value-source-server,value source server>>.

include::../requirements/requirements_class_collection-input.adoc[]

The following requirements describe how an <<execute-request-body,execute request>> references an <<def_collection,OGC API accessible collection>> and how an implementation requests data from that collection to use as input to a process.

[[sc_collection-input_referencing]]
==== Referencing a collection

include::../requirements/collection-input/REQ_collection-input_referencing.adoc[]

[[sc_collection-input_access]]
==== Accessing data from a collection

[[sc_collection-input_access-overview]]
===== Overview

The following requirements describe how to access data from an <<def_collection,OGC API accessible collection>> and the ability of an implementation to modify the accessed data by first applying filters, selecting a subset of fields or deriving new fields before providing the data as input to a process.

include::../requirements/collection-input/REQ_collection-input_access.adoc[]

[[sc_collection-input_filtering]]
===== Filtering

include::../requirements/collection-input/REQ_collection-input_filtering.adoc[]

NOTE: The server may also do some intelligent remapping of parameters.  For example, if a `bbox` parameter is specified in the execute request, but the <<def_value-source-server,value source server>> only supports the `geometry` parameter, the implementation may convert the bounding box to a 4-point polygon and map the specified `bbox` parameter to the `geometry` parameter supported by the <<def_value-source-server,value source server>>.

[[sc_collection-filtering_filter]]
====== Parameter `filter`

A search or filter condition.  This condition determines which resources from the OGC API collection are included in the result set and are thus passed as values to the corresponding process input.  The `filter` parameter can be a string where the search condition is encoded in some text-based query language (e.g. cql2-text) or a CQL2 JSON object that encodes the search condition using JSON.

[[sc_collection-filtering_filter-crs]]
====== Parameter `filterCrs`

Asserts the CRS used for the coordinate values of the `filter` parameter.  The default is WGS 84 or WGS 84h depending on whether ellipsoidal height is included with the coordinates or not:

* WGS 84 longitude/latitude (https://www.opengis.net/def/crs/OGC/1.3/CRS84)
* WGS 84h longitude/latitude/ellipsoidal height (https://www.opengis.net/def/crs/OGC/0/CRS84h_

[[sc_collection-filtering_filter-lang]]
====== Parameter `filterLang`

Indicates the language used to encode a filter expression specified using the `filter` parameter. Query languages can include CQL2 text, CQL 2 JSON or OGC Filter Encoding (XML).

[[sc_collection-filtering_bbox]]
====== Parameter `bbox`

Only resources that have a geometry that intersects the bounding box are selected to be passed as input values to an executing process.  If a resource has multiple spatial geometry properties, it is the decision of the value source server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.

[[sc_collection-filtering_bbox-crs]]
====== Parameter `bboxCrs`

Asserts the CRS used for the coordinate values of the `bbox` parameter.  The default is WGS 84 or WGS84h depending on whether ellipsoidal height is included or not:

* WGS 84 longitude/latitude [4 numbers]
  (https://www.opengis.net/def/crs/OGC/1.3/CRS84)
* WGS 84h longitude/latitude/ellipsoidal height [6 numbers]
  (https://www.opengis.net/def/crs/OGC/0/CRS84h_

[[sc_collection-filtering_datetime]]
====== Parameter `datetime`

Either a date-time or an interval, half-bounded or bounded. Date and time expressions adhere to <<rfc3339,IETF RFC 3339>>. Half-bounded intervals are expressed using double-dots.  Only resources that have a temporal property that intersects the value of `datetime` are selected.  If a resource has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties.

[[sc_collection-filtering_subset]]
====== Parameter `subset`

Retrieve only part of the data by slicing or trimming along one or more axis. For specifying a trim operation: `{axisAbbrev}({low}:{high})` (preserves dimensionality). An asterisk (`*`) can be used instead of `{low}` or `{high}` to indicate the minimum/maximum value. For expression a slice operation: `{axisAbbrev}({value})` (reduces dimensionality).

[[sc_collection-filtering_subset-crs]]
====== Parameter `subsetCrs`

Asserts the CRS used for the coordinate values of the `subset` parameter.  The default is WGS 84 or WGS 84h depending on whether ellipsoidal height in included with the coordinates or not:

* WGS 84 longitude/latitude (`https://www.opengis.net/def/crs/OGC/1.3/CRS84`)
* WGS 84h longitude/latitude/ellipsoidal height (`https://www.opengis.net/def/crs/OGC/0/CRS84h`)

[[sc_collection-filtering_geometry]]
====== Parameter `geometry`

Only resources that have a geometry that intersects the geometry specified using the `geometry` parameter are selected.  The value of the `geometry` parameter can be specified using Well Known Text (WKT) or GeoJSON.  If a resource has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.

[[sc_collection-filtering_geometry-crs]]
====== Parameter `geometryCrs`

Asserts the CRS used for the coordinate values of the `geometry` parameter.  The default is WGS 84 or WGS84h depending on whether ellipsoidal height is included or not:

* WGS 84 longitude/latitude (`https://www.opengis.net/def/crs/OGC/1.3/CRS84`)
* WGS 84h longitude/latitude/ellipsoidal height (`https://www.opengis.net/def/crs/OGC/0/CRS84h`)

[[sc_collection-filtering_limit]]
====== Parameter `limit`

The optional limit parameter limits the number of items that are presented in the response document.  Only items are counted that are on the first level of the collection in the response document.  Nested objects contained within the explicitly requested items shall not be counted.

[[sc_collection-filtering_ids]]
====== Parameter `ids`

The optional `ids` parameter allows a specific list of resources, indicated by their identifiers, to be fetched from an OGC API accessible collection. Only resources whose identifier matches one of the values listed for this parameter shall appear in the result set.

[[sc_collection-filtering_q]]
====== Parameter `q`

The optional `q` parameter supports keyword searching.  Only resources whose text fields contain one or more of the specified search terms are selected.  The specific set of text keys/fields/properties of a resource to which the `q` operator is applied is up to the discretion of the server.  Implementations should, however, apply the `q` operator to the title, description and keywords keys/fields/properties if they exist in the resource.

[[sc_collection-filtering_assets]]
====== Parameter `assets`

The optional `assets` parameter indicates which assets to select from a list of potential candidates found within the Collection. While not necessarily limited to STAC, it is a common example for illustrative purpose. The `assets` would indicate the STAC Assets to select by name from a STAC Collection where Items offer multiple Assets. The Assets can be resolved at the Collection level (i.e., `item_assets` or `assets`) or from individual Items. This selection is to be distinguished from <<sc_collection-filter_property-selection,property selection>> where the fields of those filtered `assets` are selected instead. The `assets` field might not apply to certain collection formats dealing directly with the data properties.

[[sc_collection-filtering_crs]]
====== Parameter `crs`

If the parameter is specified, then the coordinates of all geometry-valued properties in a response document are in the requested CRS. Otherwise the coordinates are in the default CRS, that is `https://www.opengis.net/def/crs/OGC/1.3/CRS84` for coordinates without height and `https://www.opengis.net/def/crs/OGC/0/CRS84h` for coordinates with ellipsoidal height.

[[sc_collection-filter_property-selection]]
===== Property selection & derived properties

include::../requirements/collection-input/REQ_collection-input_property-selection.adoc[]

[[sc_collection-filter_property-selection-properties]]
====== Parameter `properties`

A filter that selects resource properties to be included in a response document.  The elements in the `properties` parameter can be the names of resource properties, aliases for resources properties or synthetic properties.  Synthetic properties are properties that are computed on the fly and can reference resource property names or aliases for resource properties.

[[sc_collection-filter_property-selection-aliases]]
====== Parameter `aliases`

A dictionary of `aliases` that can be used as values for the `properties` parameter.  Aliases can be alternative names for resource properties or synthetic properties.  Synthetic properties are named expressions that are computed at run-time.  Expressions for synthetic properties are encoded using some expression language and can include references to resource property names or aliases for resource properties.

[[sc_collection-input_pass-through]]
===== Pass through parameters

include::../requirements/collection-input/REQ_collection-input_pass-through.adoc[]

The `passThroughParameters` property is a dictionary of query parameters that are passed directly to the value source server.  The keys used in this object should be identical to query parameters that the value source server recognizes.

In the case where the OAProc server supports local filtering, the `passThroughParameters` property provides a mechanism to force filtering to occur on the value source server.

[[sc_collection-input_examples]]
==== Examples

.An example execute request with collection input
====
[source,json]
----
include::../examples/json/Execute2.json[]
----
====


[[sc_remote-collections]]
=== REQUIREMENTS CLASS "REMOTE COLLECTIONS"

[[sc_remote-collections_overview]]
==== Overview

The _Remote Collections_ Requirements Class allows to reference a remote OGC API accessible collection in addition to any local collections.

include::../requirements/requirements_class_remote-collections.adoc[]

The following requirements describe how an <<execute-request-body,execute request>> references a <<def_remote-collections,remote OGC API accessible collection>> as a source of input values to a process.

[[sc_remote-collections_referencing]]
==== Referencing a remote collection

include::../requirements/remote-collections/REQ_remote-collections_referencing.adoc[]

[[sc_remote-collections_access]]
==== Accessing data from a remote collection

include::../requirements/remote-collections/REQ_remote-collections_access.adoc[]

[[sc_remote-collections_filtering]]
===== Filtering

See: <<sc_collection-input_filtering,Filtering>>

[[sc_remote-collections_property-selection]]
===== Property selection & derived properties

See: <<sc_collection-filter_property-selection,Property selection & derived properties>>

[[sc_remote-collections_pass-through]]
===== Pass through parameters

See: <<sc_collection-input_pass-through,Pass through parameters>>

[[sc_collection-output]]
=== REQUIREMENTS CLASS "COLLECTION OUTPUT"

[[sc_collection-output_overview]]
==== Overview

The _Collection Output_ Requirements Class specifies how the execution of a process can be triggered as the result of requesting output data using an <<def_data-access-mechanism,OGC API data access mechanisms>>.

This provides an alternative to the synchronous and asynchronous execution mechanisms defined in this Standard for which spatial, temporal and other filtering parameters would need to be hardcoded in the <<execute-request-body,execute request>>.  When lengthy batch processing is not desirable, completely new <<execute-request-body,execute requests>> each with different spatial, temporal and other filtering parameters and returning a partial output would need to be continuously re-submitted.

This conformance class supports submitting an <<execute-request-body,execute request>> once and then accessing the output using <<def_data-access-mechanism,OGC API data access mechanisms>> in a manner that is  completely agnostic of process execution.

Compared to separate <<execute-request-body,execute requests>>, this mechanism makes it easier for implementations to optimize for scenarios where small partial outputs are streamed from the same pre-established processing pipeline. Parsing the <<execute-request-body,execute request>>, validating inputs, and handshakes with remote components only needs to be performed once. An implementation could also preempt future requests based on past requests, offsetting the latency of a complex processing pipeline.

include::../requirements/requirements_class_collection-output.adoc[]

The following requirements describe an execution mechanism that triggers on-demand processing for particular spatial, temporal and other filtering parameters and results in one or more references to a <<def_collection-description,collection description document>> that provides links to request output data using standard <<def_data-access-mechanism,OGC API data access mechanisms>>.

[[sc_collection-output_response]]
==== Parameter `response`

include::../requirements/collection-output/REQ_collection-output_response-def.adoc[]

include::../recommendations/collection-output/PER_collection-output_response-query.adoc[]

include::../requirements/collection-output/REQ_collection-output_response-output-one.adoc[]

include::../recommendations/collection-output/PER_collection-output_response-output-one.adoc[]

include::../requirements/collection-output/REQ_collection-output_response-output-many-results.adoc[]

include::../requirements/collection-output/REQ_collection-output_response-output-many-grouped.adoc[]

[NOTE]
=====
The <<req_collection-output_response-output-many-grouped,/req/collection-output/response-output-many-grouped>> part mentioning aggregation is left up to server implementations to negotiate and resolve as deemed fit. For example, a process generating multiple GeoTiff rasters as separate bands per output and requesting the collection output could either aggregate each band as separate Assets under a _STAC Collection_ and/or _STAC Items_, or could generate an _OGC API - Coverages_ collection by combining bands over corresponding extents. The specific separation of STAC Collection/Items/Assets, Coverage granules, or any other aggregation strategy is out of scope for this standard. However, <<sc_con-neg-by-profile>> would realistically play a role in this process to further distinguish possible combinations and expected outcomes.
=====

[[sc_collection-output_error-situations]]
==== Error Situations

include::../requirements/collection-output/REQ_collection-output_response-unsupported-format.adoc[]

[[sc_collection-output_data-access-mechanisms]]
==== Data Access Mechanisms

include::../requirements/collection-output/REQ_collection-output_data-access-mechanisms.adoc[]

This Standard does not impose any particular approach to materializing output <<def_collection,collections>> resulting from a process execution request.

include::../recommendations/collection-output/PER_collection-output_static.adoc[]

include::../recommendations/collection-output/PER_collection-output_dynamic.adoc[]

[[sc_collection-output_expiry]]
==== Collection Output expiry

include::../recommendations/collection-output/PER_collection-output_expiry.adoc[]

[[sc_local-filtering]]
=== REQUIREMENTS CLASS "LOCAL FILTERING"

[[sc_local-filtering_overview]]
==== Overview

As described in <<sc_collection-input_filtering>>, implementation of this Standard that support <<sc_collection-input,collection input>> rely on the <<def_value-source-server,value source server>> to perform any input data filtering specified in an execution request.

Servers that implement this Requirements Class, support local filtering in those instances where the <<def_value-source-server,value source server>> does not support the input data filtering requested in the execution request.

include::../requirements/requirements_class_local-filtering.adoc[]

[[sc_local-filtering_filter-parameters]]
==== Filter parameters

include::../requirements/local-filtering/REQ_local-filtering.adoc[]
