
== Requirements classes for encodings

////
for now, normative statements are often included inline. This will be re-factored later.
////

=== Overview

This clause specifies two pre-defined requirements classes for request and response message encodings to be used by implementations the Processes API. The two classes are:

* <<sc_requirements_class_json,JSON>>
* <<sc_requirements_class_html,HTML>>

The <<sc_requirements_class_json,JSON>> requirements class defines the requirements for encoding Processes API request and response messages using https://tools.ietf.org/html/rfc8259[JSON].

The <<sc_requirements_class_json,HTML>> requirements class defines the requirements for encoding Processes API request and response messages using https://html.spec.whatwg.org/[HTML].

NOTE: The encoding of Processes API request and response messages is distinct from the values that are generated when executing a process.  Process output values can be of any type and are not bound by the requirements of the classes defined in this clause.

NOTE: Any server that supports multiple encodings (JSON or HTML defined in this Standard or other encodings not specified in this Standard) will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any approach as to how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation detail and the mechanism as to how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.

[NOTE]
====
Two common approaches are:

* An additional path for each encoding of each resource (this can be expressed,
for example, using format specific suffixes like `.html`);

* An additional query parameter (for example, "accept" or "f") that overrides
the Accept header of the HTTP request.
====

The <<rc_core,Core>> requirements class includes recommendations to support
<<rc_html,HTML>> and <<rc_json,JSON>> as encodings, where practical.


[[sc_requirements_class_json]]
=== Requirement Class "JSON"

This section defines the requirements class JSON.

include::../requirements/requirements_class_json.adoc[]

include::../requirements/json/REQ_definition.adoc[]


[[sc_requirements_class_html]]
=== Requirement Class "HTML"

This section defines the requirements class HTML.

include::../requirements/requirements_class_html.adoc[]

include::../requirements/html/REQ_definition.adoc[]

include::../requirements/html/REQ_content.adoc[]
