[[ats_core_job-creation-sync-raw-ref]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-creation-sync-raw-ref
subject:: <<req_core_job-creation-sync-raw-ref,/req/core/job-creation-sync-raw-ref>>
test-purpose:: Validate that the server responds as expected when synchronous execution is <<sc_execution_mode,negotiated>>, the response type is `raw` and the transmission mode is `ref`.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====
[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process and identify the subset of processes that support the `sync-execute` job control option and the `reference` output transmission.
--

[.component,class=step]
--
For each identified process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> ensuring that synchronous execution is <<sc_execution_mode,negotiated>> according to test <<ats_core_job-creation-default-execution-mode,/conf/core/job-creation-default-execution-mode>>, that the requested response type is `raw` (i.e. `"response": "raw"`) and the transmission mode is set to `ref` (i.e. `"transmissionMode": "ref"`) according to requirement <<req_core_job-creation-sync-raw-ref,/req/core/job-creation-sync-raw-ref>>.
--

[.component,class=step]
--
Verify that each process executes successfully according to requirement <<req_core_job-creation-sync-raw-ref,/req/core/job-creation-sync-raw-ref>>.
--
=====
====
