[[ats_core_landingpage-success]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/landingpage-success
target:: /req/core/landingpage-success
test-purpose:: Validate that the landing page complies with the require structure and contents.
test-method::
+
--
1. Validate that a document was returned with an HTTP status code or 200.

2. Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>

3. For formats that require manual inspection, perform the following:

   a. Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.

   b. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.

   c. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/processes" link to the list of processes.
--
====

NOTE: The landing page may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the landing page against that schema. All supported formats should be exercised.

[[landing-page-schema]]
.Schema and Tests for Landing Pages
[cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/landingPage.yaml[landingPage.yaml] |<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/landingPage.yaml[landingPage.yaml] |<<ats_json_content,/conf/json/content>>
|===
