[[ats_core_process-description-success]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/process-description-success
target:: /req/core/process-description-success
test-purpose:: Validate that the content complies with the required structure and contents.
test-method::
+
--
1. Validate that a document was returned with an HTTP status code of 200.

2. Verify that the content of the response is valid description of the interface of the process for all supported process description models.
--
====

NOTE: The interface of a process may be described using one of a number of different models or process description languages. The following table identifies the applicable schema document for each process description model described in this standard.

[[process-description-model]]
.Schema and Tests for Process Description Models
[cols="3",options="header"]
|===
|Model |Schema Document |Test ID
|OGC Process Description JSON|link:http://schemas.opengis.net/ogcapi/features/part1/2.0/openapi/schemas/process.yaml[process.yaml] |<<req_ogc-process-description_json-encoding,/conf/ogc-process-description/json-encoding>>
|===
