[[ats_core_process-execute-input-inline-object]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/process-execute-input-inline-object
target:: /req/core/process-execute-input-inline-object
test-purpose:: Validate that inputs with a complex object schema encoded in-line in an <<execute-request-body,execute request>> are correctly processed.
test-method::
+
--
1. Get a description of each process offered by the server using test <<ats_core_process-description-op,/conf/core/process-description-op>>.

2. Inspect the description of each process and identify the subset of processes that have inputs with complex `object schemas (i.e. inputs of type `object`).

3. For each identified process construct an <<execute-request-body,execute request>> according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode the identified object inputs in-line in the <<execute-request-body,execute request>> according to requirement <<req_core_process-execute-input-inline-object,/req/core/process-execute-input-inline-object>>.

4. Verify that each process executes successfully according to the relevant requirement (one of: <<ats_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<ats_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>) based on the combination of execute parameters.
--
====
