[[ats_core_process-execute-auto-execution-mode]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/process-execute-auto-execution-mode
target:: <<req_core_process-execute-op,/req/core/process-execute-op>>
test-purpose:: Validate that the server correctly handles the execution mode for a process.
test-method::
+
--
1. Get a description of each process offered by the server using test <<ats_core_process-description,/conf/core/process-description>>.

2. Inspect the description of each process and take note of the job control options for the process.

3. Setting the HTTP `Prefer` header to include the `respond-sync` preference, construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>>.

4. For processes that are supposed to execute asynchronously according to the <<req_core_process-execute-auto-execution-mode,/req/core/process-execute-auto-execution-mode>> requirement, verify the successful execution according to the <<ats_core_process-execute-success-async,/req/core/process-execute-success-async>> test.

5. For processes that are supposed to execute synchronously according to the <<req_core_process-execute-auto-execution-mode,/req/core/process-execute-auto-execution-mode>> requirement, verify the successful execution according to the relevant requirement (one of: <<ats_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>) based on the combination of execute parameters.

6. For processes that may execute either synchronously or asynchronously according to the <<req_core_process-execute-auto-execution-mode,/req/core/process-execute-auto-execution-mode>> requirement, verify the successful execution according to the relevant requirement (one of: <<ats_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<ats_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>) based on the combination of execute parameters.
--
====
