[[ats_core_process-execute-input-inline-bbox]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/process-execute-input-inline-bbox
target:: /req/core/process-execute-input-inline-bbox
test-purpose:: Validate that inputs with a bounding box schema encoded in-line in an execute request are correctly processed.
test-method::
+
--
1. Get a description of each process offered by the server using test <<ats_core_process-description,/conf/core/process-description>>.

2. Inspect the description of each process and identify the subset of processes that have bounding box inputs that are supposed to conform to the https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/bbox.yaml[bbox.yaml] schema.

3. For each identified process construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode values for the identified bounding box inputs in-line in the execute request.

4. Verify that each process execute successfulle according to the relevant requirement (one of: <<ats_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<ats_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>) based on the combination of execute parameters.
--
====
