[[ats_core_job-creation-input-validation]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-creation-input-validation
subject:: <<req_core_job-creation-input-validation,/req/core/job-creation-input-validation>>
test-purpose:: Verify that the server correctly validates process input values according to the definition obtained from the <<sc_process_description,process description>>.

[.component,class=test method]
=====

[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process taking note of the definition of each process input and specifically the schema of each process input.
--

[.component,class=step]
--
For each process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> taking care to encode the input values according to the schema from the definition of each input.
--

[.component,class=step]
--
Verify that each process executes successfully according to the <<ats-job-creation-success-sync,relevant requirement based on the combination of execute parameters.>>
--

[.component,class=step]
--
For each process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> taking care to encode some of the input values in violation of the schema from the definition of the selected input.
--

[.component,class=step]
--
Verify that each process generates an exception report that identifies the improperly specified input value(s).
--
=====
====
