[[ats_core_job-results-failed]]
[requirement,type="abstracttest",label="/conf/core/job-results-failed",subject='<<req_core_job-results-failed,/req/core/job-results-failed>>']
====
[.component,class=test-purpose]
--
Validate that the job results for a failed job complies with the require structure and contents.
--

[.component,class=test-method]
--
. Create a job as per <<atd_core_job-creation-op,/req/core/job-creation-op>> but arrange a priori that the job will fail; note the {jobID} assigned to the job.
. Ensure that the failed job will not result in an HTTP error code of 404.
. Issue an HTTP GET request to the URL '/jobs/{jobID}/results'.
. Validate that the document was returned with a HTTP error code (4XX or 5XX).
. Validate that the document contains an exception `type` that corresponds to the reason the job failed (e.g. InvalidParameterValue for invalid input data).
. Validate the document for all supported media types using the resources and tests identified in <<job-results-failed-schema>>
--

The job results page for a job may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the job results for a failed job against that schema.  All supported formats should be exercised.
====

[[job-results-failed-schema]]
.Schema and Tests for the Job Result for a Failed Job
[cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/exception.yaml[exception.yaml] |<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/exception.yaml[exception.yaml] |<<ats_json_content,/conf/json/content>>
|===
