[[ats_core_job-creation-sync-raw-mixed-multi]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-creation-sync-raw-mixed-multi
subject:: <<req_core_job-creation-sync-raw-mixed-multi,/req/core/job-creation-sync-raw-mixed-multi>>
test-purpose:: Validate that the server responds as expected when synchronous execution is <<sc_execution_mode,negotiated>>, the response type is `raw` and the output transmission is a mix of `value` and `reference`.

[.component,class=test method]
=====
[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process and identify the subset of processes that generate more that one output and support the `sync-execute` job control option.
--

[.component,class=step]
--
For each identified process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> ensuring that synchronous execution is <sc_execution_mode,negotiated>> according to test <<ats_core_job-creation-default-execution-mode,/conf/core/job-creation-default-execution-mode>>, that more than one output is requested, that the requested response type is `raw` (i.e. `"response": "raw"`) and the the transmission mode is a mix of `value` (i.e. `"transmissionMode": "value"`) and reference (i.e. `"transmissionMode": "reference"`) according to requirement <<req_core_job-creation-sync-raw-mixed-multi,/req/core/job-creation-sync-raw-mixed-multi>>.
--

[.component,class=step]
--
Verify that each process executes successfully according to requirement <<req_core_job-creation-sync-raw-mixed-multi,/req/core/job-creation-sync-raw-mixed-multi>>.
--

[.component,class=step]
--
For each output requested with `"transmissionMode": "value"` verify that the body of the corresponding part contains the output value.
--

[.component,class=step]
--
For each output requested with `"transmissionMode": "reference"` verify that the body of the corresponding part is empty and the `Content-Location` header is included that points to the output value.
--
=====
====


