[[ats_core_process-execute-input-validation]][abstract_test]
====
[%metadata]
label:: /conf/core/process-execute-input-validation
subject:: <<req_core_process-execute-input-validation,/req/core/process-execute-input-validation>>
test-purpose:: Verify that the server correctly validates process input values according to the definition obtained from the <<sc_process_description,process description>>.

[.component,class=test method]
=====

[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process taking note of the definition of each process input and specifically the schema of each process input.
--

[.component,class=step]
--
For each process construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode the input values according to the schema from the definition of each input.
--

[.component,class=step]
--
Verify that the server successfully executes each process according to the tests <<ats_core_process-execute-sync-one,/conf/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-many-json,/conf/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one-default-content,/conf/core/process-execute-sync-one-default-content>> or <<ats_core_process-execute-success-async,/conf/core/process-execute-success-async>> based on the combination of execute parameters used in each case.
--

[.component,class=step]
--
For each process construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode some of the input values in violation of the schema from the definition of the selected input.
--

[.component,class=step]
--
Verify that the server generates an exception report that identifies the improperly specified input value(s).
--
=====
====
