[[ats_core_job-creation-sync-raw-value-multi]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-creation-sync-raw-value-multi
subject:: <<req_core_job-creation-sync-raw-value-multi,/req/core/job-creation-sync-raw-value-multi>>
test-purpose:: Validate that the server responds as expected when synchronous execution is <<sc_execution_mode,negotiated>>, the response type is `raw` and the output transmission is `value`.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====
[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process and identify the subset of processes that generate more that one output, support the `sync-execute` job control option and the `value` output transmission.
--

[.component,class=step]
--
For each identified process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> ensuring that synchronous execution is <sc_execution_mode,negotiated>> according to test <<ats_core_job-creation-default-execution-mode,/conf/core/job-creation-default-execution-mode>>, that more than one output is requested, that the requested response type is `raw` (i.e. `"response": "raw"`) and the the transmission mode is set to `value` (i.e. `"transmissionMode": "value"`) according to requirement <<req_core_job-creation-sync-raw-value-multi,/req/core/job-creation-sync-raw-value-multi>>.
--

[.component,class=step]
--
Verify that each process executes successfully according to requirement <<req_core_job-creation-sync-raw-value-multi,/req/core/job-creation-sync-raw-value-multi>>.
--
=====
====
