[[ats_core_job-results-exception-results-not-ready]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-results-exception-results-not-ready
subject:: <<req_core_job-results-exception-results-not-ready,/req/core/job-results-exception-results-not-ready>>
test-purpose:: Validate that the job results retrieved for an incomplete job complies with the require structure and contents.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====

[.component,class=step]
--
Create a job as per <<ats_core_job-creation-op,/req/core/job-creation-op>> and note the {jobID} assigned to the job; ensure that the job is long-running.
--

[.component,class=step]
--
Issue an HTTP GET request to the URL '/jobs/{jobID}/results' before the job completes execution.
--

[.component,class=step]
--
Validate that the document was returned with a 404.
--

[.component,class=step]
--
Validate that the document contains the exception `type` "http://www.opengis.net/def/exceptions/ogcapi-processes-1/1.0/result-not-ready".
--

[.component,class=step]
--
Validate the document for all supported media types using the resources and tests identified in <<job-results-exception-results-not-ready>>
--
=====

The job results page for a job may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the job results for an incomplete job against that schema.  All supported formats should be exercised.
====

[[job-results-exception-results-not-ready]]
.Schema and Tests for the Job Result for an Incomplete Job
[cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/exception.yaml[exception.yaml] |<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/exception.yaml[exception.yaml] |<<ats_json_content,/conf/json/content>>
|===
