[[ats_core_process-execute-input-array]][abstract_test]
====
[%metadata]
label:: /conf/core/process-execute-input-array
subject:: <<req_core_process-execute-input-array,/req/core/process-execute-input-array>>
test-purpose:: Verify that the server correctly recognizes the encoding of parameter values for input parameters with a maximum cardinality greater than one.

[.component,class=test method]
=====
[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process and identify the list of processes that have inputs with a maximum cardinality greater that one.
--

[.component,class=step]
--
For each identified process construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode the inputs with maximum cardinality > 1 according to the requirement <<req_core_process-execute-input-array,/req/core/process-execute-input-array>>.
--

[.component,class=step]
--
Verify that the server successfully executes each identified process according to the tests <<ats_core_process-execute-sync-one,/conf/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-many-json,/conf/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one-default-content,/conf/core/process-execute-sync-one-default-content>> or <<ats_core_process-execute-success-async,/conf/core/process-execute-success-async>> based on the combination of execute parameters used in each case.
--
=====
====
