[[ats_core_process-execute-input-array]]

[abstract_test]
====
[%metadata]
identifier:: /conf/core/process-execute-input-array
target:: /req/core/process-execute-input-array
test-purpose:: Verify that the server correctly recognizes the encoding of parameter values for input parameters with a maximum cardinality greater than one.
test-method::
+
--
1. Get a description of each process offered by the server using test <<ats_core_process-description,/conf/core/process-description>>.

2. Inspect the description of each process and identify the list of processes that have inputs with a maximum cardinality greater that one.

3. For each identified process construct an execute request according to test <<ats_core_process-execute-request,/conf/core/process-execute-request>> taking care to encode the inputs with maximum cardinality > 1 according to the requirement <<req_core_process-execute-input-array,/req/core/process-execute-input-array>>.

4. Verify that each process executes successfully according to the relevant requirement (one of: <<ats_core_process-execute-success-async,/req/core/process-execute-success-async>>, <<ats_core_process-execute-sync-many-json,/req/core/process-execute-sync-many-json>>, <<ats_core_process-execute-sync-one,/req/core/process-execute-sync-one>>, <<ats_core_process-execute-sync-one-default-content,/req/core/process-execute-sync-one-default-content>>) based on the combination of execute parameters.
--
====
