[[ats_core_job-results-async-raw-value-multi]]
[abstract_test]
====
[%metadata]
label:: /conf/core/job-results-async-raw-value-multi
subject:: <<req_core_job-results-async-raw-value-multi,/req/core/job-results-async-raw-value-multi>>
test-purpose:: Validate that the server responds as expected when asynchronous execution is <sc_execution_mode,negotiated>>, more than one output is requested, the response type is `raw` and the output transmission is `value`.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====
[.component,class=step]
--
Get a description of each process offered by the server using test <<ats_core_process,/conf/core/process>>.
--

[.component,class=step]
--
Inspect the description of each process and identify the subset of processes that generate more than one output and that support the `async-execute` job control option and the `value` output transmission.
--

[.component,class=step]
--
For each identified process construct an execute request according to test <<ats_core_job-creation-request,/conf/core/job-creation-request>> ensuring that asynchronous execution is <<sc_execution_mode,negotiated>> according to test <<ats_core_job-creation-auto-execution-mode,/conf/core/job-creation-auto-execution-mode>>, that the requested response type is `raw` (i.e. `"response": "raw"`) and that the output transmission is set to `value` (i.e. `"outputTransmission": "value"`) according to requirement <<req_core_job-creation-async-raw-value-multi,/req/core/job-creation-async-raw-value-multi>>.
--

[.component,class=step]
--
Periodically retrieve the status of the asynchronously execute job as per test <<ats_core_job-op,/conf/core/job-op>>.
--

[.component,class=step]
--
When the job status is `successful`, get the results as per test <<ats_core_job-results-op,/conf/core/job-results>> and verify that they conform to requirement <<req_core_job-results-async-raw-value-multi,/conf/core/job-results-async-raw-value-multi>>.
--
=====

NOTE: In the case where a process supports both `async-execute` and `sync-execute` job control options there is a possibility that the server responds synchronously even though the `Prefer` headers asserts a `respond-async` preference.  In this case, the following additional test should be performed.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====

[.component,class=step]
--
Inspect the headers of the synchronous response and see if a `Link` header is included with `rel=monitor`.
--

[.component,class=step]
--
If the link exists, get the job status as per test <<ats_core_job-op,/conf/core/job-op>> and ensure that the job status is set to `successful`.
--

[.component,class=step]
--
Get the results as per test <<ats_core_job-results-op,/conf/core/job-results>> and verify that they conform to the test <<ats_core_job-results-async-raw-value-multi,/conf/core/job-results-async-raw-value-multi>>.
--

[.component,class=step]
--
If the link does not exist then verify that the synchronous response conforms to requirement <<req_core_job-creation-sync-raw-value-multi,/req/core/job-creation-sync-raw-value-multi>>.
--
=====
====



