[[req_job-list_duration-response]]
[.requirement,label="/req/job-list/status-response"]
====
[.requirement,label="Condition"]
=====
. If the `status` parameter is not specified then only jobs that are running (status: `running`) or have completed execution (`successful`, `failed` or `dismissed`) SHALL be considered for inclusion in the response.
. If the `status` parameter is specified, then only jobs with the speecified status SHALL be considered for inclusion in the response.
=====

[.requirement,label="A"]
=====
If only the `minDuration` parameter is specified with the operation, only jobs with the appropriate status and a duration of at least the specified `minDuration` value SHALL be included in the response.
=====

[.requirement,label="B"]
=====
If only the `maxDuration` parameter is specified with the operation, only jobs with the appropriate status and a duration of no longer than the specified `maxDuration` value SHALL be included in the response.
=====

[.requirement,label="C"]
=====
If both the `minDuration` and `maxDuration` parameters are specified with the operation, only jobs with the appropriate status and a duration of at least the specified `minDuration` value and no longer than the specified `maxDuration` value SHALL be included in the response.
=====

[.requirement,label="D"]
=====
The value of the `minDuration` and `maxDuration` parameters SHALL be number of seconds.
=====

[.requirement,label="E"]
=====
For running jobs, the duration SHALL be computed at runtime as the time the operation was invoked minus the value of the `started` parameter  (see: https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/statusInfo.yaml[statusInfo.yaml]).
=====

[.requirement,label="F"]
=====
For completed jobs, the duration SHALL be computed as the value of the `finished` parameter minus the value of the `started` parameter  (see: https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/statusInfo.yaml[statusInfo.yaml]).
=====

[.requirement,label="G"]
=====
Jobs for which runtime statistics are not included in the https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/statusInfo.yaml[status information] or are incomplete for computing the duration of the job SHALL be omitted from the response.
=====
====
