[[ats_collection-output_response-output-many-grouped]]
[abstract_test]
====
[%metadata]
identifier:: /conf/collection-output/response-output-many-grouped
target:: /req/collection-output/response-output-many-grouped
test-purpose:: Validate that the response for multiple <<implicit-explicit-outputs,explicitly or implicitly>> requested outputs combines the outputs into a single <<def_collection-description,collection description>> reference.
test-method::
+
--
1. Obtain a process description for one or more processes offered by the server as per test <<ats_core_process-description-op,/conf/core/process-description-op>>.

2. Inspect the description of the outputs of each process and identify those outputs that support multiple collection outputs (e.g. see test <<ats_ogc-process-description_data-access-apis,/conf/ogc-process-description/data-access-apis>>).

3. Compose an execute request (see: <<ats_core_process-execute-op,/conf/core/process-execute-op>>) for each identified process and request multiple outputs identified in Step 2.  Ensure that the execution endpoint (i.e. `/processes/{processID}/execution`) includes the `response=collection` query parameter.

4. Verify that the server responds with an HTTP status code of 303.

5. Verify that the response includes a `Location` header referring to the produced <<def_collection-description,collection description>> output.

6. Verify that the response includes a HTTP header `Link: href="https://www.opengis.net/def/profile/OGC/0/ogc-collection", rel="profile"`.

7. Verify that the referenced <<def_collection-description,collection description>> includes all requested outputs.

--
====
