[[ats_collection-output_response-response-many]]
[abstract_test]
====
[%metadata]
identifier:: /conf/collection-output/response-response-many
target:: /req/collection-output/response-response-many
test-purpose:: Validate that the response for multiple explicitly or implicitly requested outputs is a <<schema_results,results.yaml>> document containing references to <<def-collection-description,collection description documents>>.
test-method::
+
--
1. Obtain a process description for one or more processes offered by the server as per test <<ats_core_process-description-op,/conf/core/process-description-op>>.

2. Inspect the description of the outputs of each process and identify those outputs that support multiple collection outputs (e.g. see test <<ats_ogc-process-description_data-access-apis,/conf/ogc-process-description/data-access-apis>>).

3. Compose an execute request (see: <<ats_core_process-execute-op,/conf/core/process-execute-op>>) for each identified process and request multiple outputs identified in Step 2.  Ensure that the execution endpoint (i.e. `/processes/{processID}/execution`) includes the `response=collection` query parameter.

4. Verify that the server responds with an HTTP status code of 200.

5. Verify that the media type of the response is `application/json`.

6. Verify that the body of the response conforms to the <<schema_results,results.yaml>> schema.

7. Verify that that value of each collection output is a link to a <<def-collection-description,collection description document>>.
--
====
