[[clause_ogcapppkg]]
== Requirements Class "OGC Application Package"

[[sc_ogcapppkg_overview]]
=== Overview

include::../requirements/requirements_class_ogcapppkg.adoc[]

This requirements class defines the schema of an `OGC Application Package`.

An `OGC Application Package` is a document that describes a process in sufficient
detail so that an implementation of this Standard can dynamically deploy that
process and make it accessible via an the processes API defined in https://fix.me["OGC API - Processes - Part 1: Core"].

The information contained in an `OGC Application Package` includes:

* A formal description of the process including what inputs the process takes and what outputs the process generates.
* Either an inline or by-reference execution unit which describes the `code` that the server needs to execute whenever the process is invoked.
* Additional resource information the server may require in order to establish an execution environment for the execution unit.

[[sc_ogcapppkg_schema]]
=== Schema

include::../requirements/ogcapppkg/REQ_schema.adoc[]

[[sc_ogcapppkg_process-description-property]]
=== processDescription property

The formal process description (i.e. its inputs, its output, etc.) is provided via the `processDescription` property of the application package.

include::../requirements/ogcapppkg/REQ_process-description.adoc[]

NOTE: The `processDescription` property is optional and if it is not included in the application package, the process interface must be inferred from the information in the <<sc_ogcapppkg_execution-unit-property,execution unit>>.

[[sc_ogcapppkg_execution-unit-property]]
=== executionUnit property

The execution unit, specified using the <<sc_ogcapppkg_execution-unit-property,`executionUnit` property>>, describes the code that a processing server must execute whenever a mutable process is invoked.

include::../requirements/ogcapppkg/REQ_executionUnit-schema.adoc[]

Conformance classes for two types of execution units are defined in this Standard:

* execution units where the executable code is encapsulated with a container (e.g. Docker),
* execution units encoded as a workflow that is executed by some workflow runner (e.g. CWL).

include::../recommendations/ogcapppkg/REC_execution-unit-docker.adoc[]

include::../recommendations/ogcapppkg/REC_execution-unit-cwl.adoc[]

include::../recommendations/ogcapppkg/PER_other-execution-units.adoc[]

The following example illustrates an execution unit where the executable code is encapsulated in a Docker image:

[[docker_ogcapppkg_example]]
[source%unnumbered,json]
----
{
  "executionUnit": {
    "type": "docker",
    "value": {
      "image": "mydocker/ndvi:latest",
      "bindings": {
        "inputBindings": {
          "inputImage": {
            "prefix": "inputsImages=",
            "inputSeparator": ","
          }
        },
        "outputBindings": {
          "outputImage": {
            "glob": "$(\"/outputs/ndvi_\" + inputs.inputImage.basename)"
          }
        }
      },
      "deployment": "local",
      "config": {
        "cpuMin": 2,
        "cpuMax": 5,
        "memoryMin": 1,
        "memoryMax": 3
      }
    }
  }
}
----

[[sc_ogcapppkg_media-types]]
=== Media types in operations

include::../requirements/ogcapppkg/REQ_request-body.adoc[]

include::../requirements/ogcapppkg/REQ_response-body.adoc[]
