
[abstract]
== Abstract

OGC API Standards define modular API building blocks to spatially enable Web APIs in a consistent way. The <<OpenAPI-Spec,OpenAPI specification>> is used to define the API building blocks.

The OGC API Processes Standard (aka Processes API) defines API building blocks to describe, execute, monitor and retrieve results of Web-accessible processes. OGC API Processes is comprised of multiple parts, each of them is a separate OGC Standard.

OGC API - Processes - Part 2: Deploy, Replace, Undeploy extends the core capabilities specified in OGC API - Processes - Part 1: Core [<<OAProc-1>>] with the ability to dynamically add, modify and/or delete individual processes using an implementation (endpoint) of the OGC API - Processes Standard.

CAUTION: This is a DRAFT version of the 2nd part of the OGC API - Processes standards. This draft is not complete and there are open issues that are still under discussion.

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[cols="2",options="header,unnumbered"]
|===
| Name | Affiliation
| Panagiotis (Peter) A. Vretanos _(editor)_ | CubeWerx Inc.
| Gérald Fenoy _(editor)_ | GeoLabs
| Pedro Gonçalves  | Terradue Srl.
| Francis Charette Migneault | Centre de Recherche en Informatique de Montréal (CRIM)
|===
