== Requirements Class "Deploy, Replace, Undeploy"

[[deploy-replace-undeploy-overview]]
=== Overview

include::../requirements/requirements_class_deploy-replace-undeploy.adoc[]

A server that implements this conformance class provides the ability to
dynamically deploy, replace and undeploy processes from a processes API.

The HTTP POST method is used to deploy a new process to the API.

The HTTP PUT method is used to replace the definition of a previously deployed processes that is accessible via the API.

Finally, the HTTP DELETE method is used to undeploy a previously deployed process that is accessible via the API.

Deploying or replacing a process requires that a formal description of the new or
replacement process be provided by the client.  This extension does not
mandate that a specific processes description language or vocabulary be used.
However, in order to promote interoperability, this extension defines two
conformance classes:

 * <<rc_ogcapppkg,OGC Application Package>>, that defines a formal process description language encoded using JSON,
 * <<rc_cwl,CWL>>, that enables support for CWL-encoded process definition,
 
A recommendation is made later in this specification that all implementations of this extension support the `OGC Application Package`.

[[deploy-replace-undeploy-http_status_codes]]
==== HTTP status codes

API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 201 and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[[status_codes]]
.Typical HTTP status codes
[cols="15,85",options="header"]
|===
|Status code |Description
|`200` |A successful request.
|`201` |The server has been fulfilled the operation and a new resource has been created.
|`202` |The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
|`204` |A successful request with no additional content to send in the response.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`412` |The status code indicates that one or more conditions given in the request header fields evaluated to false when tested by the server.
|`413` |The server is refusing to process the request because the request content is larger than the server is willing or able to process.
|`415` |The server is refusing to service the request because the content is in a format not supported by this method on the target resource.
|`422` |The server understands the content type of the request content and the syntax of the request content is correct, but was unable to process the contained instructions. For example, the submitted resource does not meet a semantic constraint, e.g. a mandatory property is missing.
|`500` |An internal error occurred in the server.
|===

NOTE: Status code `422` is not yet an official HTTP status code, but is expected to be added by the https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-422-unprocessable-content[draft IETF RFC "HTTP Semantics"].

More specific guidance is provided for each resource, where applicable.

include::../recommendations/deploy-replace-undeploy/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[cross_origin]]
==== Cross-origin requests

See <<OAFeat-1,OGC API - Features - Part 1: Core>>, section link:http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#cross_origin[Support for cross-origin requests], about the importance of supporting cross-origin requests, typically via link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)].


=== Immutable processes

This extension recognizes that an OGC web processing API may be deployed with a set of static, built-in processes that are immutable and cannot be removed or modified via the deploy-replace-undeploy API.  In an API Description Document (e.g. OpenAPI), such process paths would not include support for the HTTP POST, PUT or DELETE methods.

However, in order to make it clear which processes in a collection (path: `/processes`) are built-in - and thus immutable - and which have been dynamically deployed, the processes collection schema is modified to add a flag indicating this aspect of a process.

include::../requirements/deploy-replace-undeploy/immutable/REQ_indicator.adoc[]

The following schema fragment extends the process summary accessible via the
`/processes` path to add the `mutable` property.

[source%unnumbered,yaml]
----
allOf:
  - $ref: "https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/processSummary.yaml"
  - type: object
    properties:
      mutable:
        type: boolean
        default: true
----

[[deploy]]
=== Deploying a new process to the API

==== Sequence diagram

The following diagram illustrates the sequence diagram for deploying
a new process to the API:


```
Client                                                        Server
  |                                                             |
  |  POST /processes   HTTP/1.1                                 |
  |  Content-Type: application/ogcapppkg+json                   |
  |                                                             |
  |  ... Body contains a formal description of the process to   |
  |      add (e.g. OGC Application Package) ...                 |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 201 Created                                       |
  |  Location: /processes/{processId}                           |
  |<------------------------------------------------------------|
```


==== Operation

include::../requirements/deploy-replace-undeploy/deploy/REQ_post-op.adoc[]

==== Request body

===== Overview

include::../requirements/deploy-replace-undeploy/deploy/REQ_body.adoc[]

include::../recommendations/deploy-replace-undeploy/deploy/PER_body.adoc[]

include::../requirements/deploy-replace-undeploy/deploy/REQ_content-type.adoc[]

See https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.5[section 3.1.1.5 of RFC 7231] for details.

===== OGC Application Package body

include::../recommendations/deploy-replace-undeploy/deploy/REC_body-ogcapppkg.adoc[]

===== CWL body

include::../recommendations/deploy-replace-undeploy/deploy/REC_body-cwl.adoc[]

==== Response

include::../requirements/deploy-replace-undeploy/deploy/REQ_response-pid.adoc[]

include::../requirements/deploy-replace-undeploy/deploy/REQ_response-success.adoc[]

include::../requirements/deploy-replace-undeploy/deploy/REQ_response-body.adoc[]

==== Exceptions

See <<deploy-replace-undeploy-http_status_codes>> for general guidance.

include::../requirements/deploy-replace-undeploy/deploy/REQ_unsupported-content-type.adoc[]

include::../requirements/deploy-replace-undeploy/deploy/REQ_response-duplicate.adoc[]

include::../requirements/deploy-replace-undeploy/deploy/REQ_response-immutable.adoc[]

[[replace]]
=== Replacing an existing processes

==== Sequence diagram

The following diagram illustrates the sequence diagram for replacing a
previously deployed processes.  The identifier of the process does not change.

NOTE: The new process definition replaced to old process definition; version control is not discussed in this standard.

```
Client                                                        Server
  |                                                             |
  |  PUT /processes/{processId}   HTTP/1.1                      |
  |  Content-Type: application/ogcapppkg+json                   |
  |                                                             |
  |  ... Body contains a formal description of the process to   |
  |      replace the existing process (e.g. OGC Application     |
  |      Package) ...                                           |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 204 OK                                            |
  |<------------------------------------------------------------|
```

==== Operation

include::../requirements/deploy-replace-undeploy/replace/REQ_put-op.adoc[]

==== Request body

==== Overview

include::../requirements/deploy-replace-undeploy/replace/REQ_body.adoc[]

include::../recommendations/deploy-replace-undeploy/replace/PER_body.adoc[]

include::../requirements/deploy-replace-undeploy/replace/REQ_content-type.adoc[]

===== OGC Application Package body

include::../recommendations/deploy-replace-undeploy/replace/REC_body-ogcapppkg.adoc[]

===== CWL body

include::../recommendations/deploy-replace-undeploy/replace/REC_body-cwl.adoc[]

==== Response

include::../requirements/deploy-replace-undeploy/replace/REQ_response.adoc[]

The status code depends on the server. If the server has replaced the process, the response is either `200`, if the response includes additional content, or `204`, if the response has no additional content.

If the server will process the replace request later, it will return a `202`. In this case, the processing can succeed or fail, without further notification to the client.

==== Exceptions

See <<deploy-replace-undeploy-http_status_codes>> for general guidance.

If the request body's media type is not supported by the server, then <<req_deploy-replace-undeploy_deploy_unsupported-content-type,/req/deploy-replace-undeploy/deploy/unsupported-content-type>> applies.

If the process with the specified identifier does not exist on the server, see requirement /req/core/process-exception/no-such-process from <<OAProc-1>>.

If the process exist but is immutable then <<req_deploy-replace-undeploy_deploy_response-immutable,/req/deploy-replace-undeploy/deploy/response-immutable>> applies.

[[undeploy]]
=== Removing a processes from the API (undeployProcess)

==== Sequence diagram

The following diagram illustrates the sequence diagram for undeploying a
previously deployed process.


```
Client                                                        Server
  |                                                             |
  |  DELETE /processes/{processId}   HTTP/1.1                   |
  |------------------------------------------------------------>|
  |                                                             |
  |  HTTP/1.1 204 OK                                            |
  |<------------------------------------------------------------|
```

==== Operation

include::../requirements/deploy-replace-undeploy/undeploy/REQ_delete-op.adoc[]

==== Response

include::../requirements/deploy-replace-undeploy/undeploy/REQ_response.adoc[]

==== Exceptions

See <<deploy-replace-undeploy-http_status_codes,HTTP status codes>> for general guidance.

If the process with the specified identifier does not exist on the server, see requirement /req/core/process-exception/no-such-process from <<OAProc-1>>.

If the process exist but is immutable then <<req_deploy-replace-undeploy_deploy_response-immutable,/req/deploy-replace-undeploy/deploy/response-immutable>> applies.
