
== Requirements Class "OGC Application Package"

[[ogcapppkg-overview]]
=== Overview

include::../requirements/requirements_class_ogcapppkg.adoc[]

This requirements class defines the schema of an `OGC Application Package`. An
`OGC Application Package` is a document that describes a process in sufficient
detail so that an implementation of this extension can dynamically deploy the
process and make it accessible via an OGC API - Processes implementation.

The information contained in an `OGC Application Package` can include:

* A formal description of the process including what inputs the process takes and what outputs the process generates.
* Either an inline or by reference execution unit which is the `code` that the server needs to execute whenever the process is invoked.
* Additional resource information required by the execution unit.

=== Deploy

==== Request body

include::../requirements/ogcapppkg/deploy/REQ_body.adoc[]

=== Replace

==== Request body

include::../requirements/ogcapppkg/replace/REQ_body.adoc[]

=== OGC Application Package schema

==== Overview

include::../requirements/ogcapppkg/REQ_schema.adoc[]

[[schema_ogcappkg]]
.link:http://schemas.opengis.net/ogcapi/processes/part2/1.0/openapi/schemas/ogcapppkg.yaml[Schema for the OGC Application Package]
[source,yaml]
----
include::../../../../openapi/schemas/processes-dru/ogcapppkg.yaml[]
----

==== processDescription property

The formal process description (i.e. its inputs, its output, etc.) is provided,
either in-line using the `processDescription` property or may be inferred from
the information provided in the <<executionUnit,execution unit>>.

include::../requirements/ogcapppkg/REQ_process-description.adoc[]

[[executionUnit]]
==== executionUnit property

The execution unit is the `code` that an implementation of the Part 2 extension needs
to execute whenever the deployed process is executed. 

If the schema defined for the executionUnit property of an OGC Application Package remains open, it may be refined in other Requirements.

include::../recommendations/ogcapppkg/REC_execution-unit-docker.adoc[]

include::../recommendations/ogcapppkg/REC_ogcapppkg_execution-unit-cwl.adoc[]

