
== Requirements Class "OGC Application Package"

[[ogcapppkg-overview]]
=== Overview

include::../requirements/requirements_class_ogcapppkg.adoc[]

This conformance class defines the schema of an `OGC Application Package`. An
`OGC Application Package` is a document that describes a process in sufficient
detail so that an implementation of this extension can dynamically deploy the
process and make it available for execution via an OGC processes API.

An `OGC Application Package` document provides all the information necessary to
deploy a process and make it accessible through the OGC API - Processes API.

The information contains in an `OGC Application Package` can include:

* A formal description of the process including what inputs the process takes and what outputs the process generates.
* Either inline or by reference an execution unit which is the `code` that the server needs to execute whenever the process is invoked.
* Additional resource information required by the execution unit.

=== OGC Application Package schema

==== Overview

include::../requirements/ogcapppkg/REQ_schema.adoc[]

[[schema_ogcappkg]]
.link:http://schemas.opengis.net/ogcapi/processes/part2/1.0/openapi/schemas/ogcapppkg.yaml[Schema for the OGC Application Package]
[source,yaml]
----
include::../../../../openapi/schemas/processes-dru/ogcapppkg.yaml[]
----

==== processDescription property

The formal process description (i.e. its inputs, its output, etc.) is provided,
either in-line using the `processDescription` property or may be infered from
the information provided in the <<executionUnit,execution unit>>.

include::../requirements/ogcapppkg/REQ_process-description.adoc[]

[[executionUnit]]
==== executionUnit property

The execution unit is the `code` that an implementation of this extensions needs
to execute whenever the deployed process is executed.  The execution unit can be
either specified in-line (e.g. CWL script) or by reference (e.g. docker image reference).

include::../requirements/ogcapppkg/REQ_execution-unit-docker.adoc[]

When CWL encoding is used, the execution unit can be either passed by value (in-line) or by reference.

include::../recommendations/ogcapppkg/REC_ogcapppkg_execution-unit-cwl.adoc[]

Below is an example of a deploy body request using a CWL-encoded execution unit by reference.

[[example1]]
[source%unnumbered]
----
{
  "executionUnit": {
    "href": "https://raw.githubusercontent.com/EOEPCA/app-snuggs/main/app-package.cwl",
    "type": "application/cwl"
  }
}
----

==== deploymentProfile property

The deploymentProfile property is used to indicate the type of execution unit
that is being provided.

include::../requirements/ogcapppkg/REQ_profile-docker.adoc[]

NOTE: I think we need to consult with the OGC NA to get a property identifier indicating that the profile is "dockerized application".

[[example2]]
[source%unnumbered]
----
{
  "processDescription": {
    "process": {
      "id": "NdviCalculation",
      "title": "Calculation of NDVI using the SNAP toolbox for Sentinel-2",
      "description": "Calculation of NDVI using the SNAP toolbox for Sentinel-2",
      "version": "1.0.0",
      "keywords": [
        "Vegetation",
        "NDVI"
      ],
      "inputs": [
        {
          "id": "source",
          "title": "Source Input Image (sentinel-2 product in SAFE format)",
          "description": "Source Input Image (sentinel-2 product in SAFE format).  Either provided inline, by reference or by product ID",
          "minOccurs": 1,
          "maxOccurs": 1,
          "input": {
            "formats": [
              {
                "mimeType": "text/plain",
                "default": true
              },
              {
                "mimeType": "application/zip",
                "default": false
              }
            ]
          }
        },
        {
          "id": "red_source_band",
          "title": "the band to be used for the red band",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "dataType": {
                  "name": "integer"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "1",
                    "maximumValue": "13",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        },
        {
          "id": "nir_source_band",
          "title": "the band to be used for the near-infrared band",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "dataType": {
                  "name": "integer"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "\n1\n",
                    "maximumValue": "13\n",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        },
        {
          "id": "red_factor",
          "title": "the factor of the NRI",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "defaultValue": "1.0\n",
                "dataType": {
                  "name": "float"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "0.0",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        },
        {
          "id": "nir_factor",
          "title": "the factor of the NIR",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "defaultValue": "1.0",
                "dataType": {
                  "name": "float"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "0.0",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        },
        {
          "id": "cloud_coverage",
          "title": "The cloud coverage of the scene.",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "dataType": {
                  "name": "float"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "0.0",
                    "maximumValue": "100.0",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        },
        {
          "id": "max_cloud_coverage",
          "title": "The maximum cloud coverage of the scene.",
          "minOccurs": 0,
          "maxOccurs": 1,
          "input": {
            "literalDataDomains": [
              {
                "default": true,
                "dataType": {
                  "name": "float"
                },
                "valueDefinition": [
                  {
                    "minimumValue": "0.0",
                    "maximumValue": "100.0",
                    "rangeClosure": "closed"
                  }
                ]
              }
            ]
          }
        }
      ],
      "outputs": [
        {
          "id": "raster",
          "title": "The raster of the resulting NDVI calculation",
          "output": {
            "formats": [
              {
                "mimeType": "image/geotiff",
                "default": true
              }
            ]
          }
        }
      ]
    },
    "jobControlOptions": [
      "async-execute"
    ],
    "outputTransmission": [
      "reference"
    ]
  },
  "executionUnit": {
    "type": "docker",
    "image": "eoc/ndvi:latest",
    "config": {
      "cpuMin": 2
    }
  },
}
----


==== Binding the process description to the invocation of the execution unit

NOTE: TBD. Need to have a discussion here about how the process inputs are mapped to the invocation of the execution unit.   Command line arguments can be expressed in many ways (e.g. '-arg value', 'arg=value', etc.) and metadata needs to be provided to tell the server how to invoke the execution unit.

NOTE: TBD. I envision this clause being composed of a series of recommendations (not requirements) based on using the `additionaParameters` property of the process description from <<OAProc-1>>.


==== Providing value hints for process inputs

NOTE: TBD. Need to have a discussion here about how hints (or perhaps stronger guidance) can be provided for process inputs.  This is beyond the kind of enum or range value that might be specified in the process description.  Rather I am thinking about being able to provide references to authoritative code lists or providing references to catalogues that can be searched for suitable values.

NOTE: TBD. I envision this clause being composed of a series of recommendations (not requirements) based on using the `metadata` property of the process description from <<OAProc-1>>.
