[[per_provenance_job-prov_content-negotiation]]
[permission]
====
[%metadata]
identifier:: /per/provenance/prov-content-negotiation

[.component,class=part]
--
Content negotiation MAY be supported to provide alternate representations of the response.
--

[.component,class=part]
--
The server MAY support the additional content type `application/ld+json`
for link:https://www.w3.org/submissions/prov-jsonld/[PROV-JSONLD] as a <<W3C-PROV>> representation
in link:https://www.w3.org/TR/json-ld/[JSON-LD], where the contents respect the
link:https://openprovenance.org/prov-jsonld/schema.json[PROV-JSONLD] schema.
--

[.component,class=part]
--
The server MAY support the additional content type `application/provenace+xml`
(and optionally `application/xml` or `text/xml` as acceptable aliases)
for link:https://www.w3.org/TR/prov-xml/[PROV-XML] as a <<W3C-PROV>> representation
in XML using namespaces defined by the link:https://www.w3.org/ns/prov.xsd[PROV-XML] schema.
--

[.component,class=part]
--
The server MAY support the additional content type `text/provenance-notation`
for link:https://www.w3.org/TR/prov-n/[PROV-N] as a human-readable provenance notation
of the link:http://www.w3.org/TR/prov-dm/[PROV-DM] data model.
--

[.component,class=part]
--
The server MAY support the additional content type `application/n-triples`
for PROV-NT as link:https://www.w3.org/TR/n-triples/[N-Triples RDF]
using the link:https://www.w3.org/TR/prov-o/[PROV-O] RDF ontology.
--

[.component,class=part]
--
The server MAY support the additional content type `text/turtle`
for PROV-TURTLE as link:https://www.w3.org/TR/rdf12-turtle/[Turtle RDF]
using the link:https://www.w3.org/TR/prov-o/[PROV-O] RDF ontology.
--

[.component,class=part]
--
For all supported content media-types, the server MAY support
link:https://datatracker.ietf.org/doc/html/rfc2616#section-12["Content Negotiation"] of the Provenance
representation either through the https://www.rfc-editor.org/rfc/rfc2616#section-14.1[HTTP Accept] header,
the `f` query parameter, by link:https://docs.ogc.org/DRAFTS/18-062r3.html#con-neg-by-profile["Profile"]
or any other mechanism it deems fit.
--

====
