[[req_core_process-execute-sync-raw-mixed-multi]]
[requirement]
====
[%metadata]
label:: /req/core/process-execute-sync-raw-mixed-multi
[.component,class=conditions]
--
. The <<sc_execution_mode,negotiated execution mode>> is synchronous, `response=raw`,
. Multiple transmission modes (`value`,`reference`) are requested.
. The number of requested outputs is more than 1.
--

[.component,class=part]
--
The server SHALL respond with an HTTP status code of 200.
--

[.component,class=part]
--
The media type of the response SHALL be `multipart/related`.
--

[.component,class=part]
--
The content of response shall conform to https://datatracker.ietf.org/doc/html/rfc2387[RFC 2387, The MIME Multipart/Related Content-type].
--

[.component,class=part]
--
Each requested output shall be encoded into one part of the response.
--

[.component,class=part]
--
The `Content-ID` header for each part SHALL be the corresponding output identifier.
--

[.component,class=part]
--
For outputs requested by reference, the `Content-Location` header SHALL be included pointing to the output and the body of the part SHALL be empty.
--

[.component,class=part]
--
For outputs requested by value, the body of the response SHALL contain the output value.
--
====
